//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatovkaSharp.Services.ExtWs
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://agw-as.cz/ats-ws/extWs/v1", ConfigurationName="DatovkaSharp.Services.ExtWs.ExtWs")]
    public interface ExtWs
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.ExtWs.extWsLogoutResponse> extWsLogoutAsync(DatovkaSharp.Services.ExtWs.extWsLogoutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://agw-as.cz/ats-ws/extWs/v1")]
    public partial class extWsLogoutRequestType
    {
        
        private string timeLimitedIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string timeLimitedId
        {
            get
            {
                return this.timeLimitedIdField;
            }
            set
            {
                this.timeLimitedIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://agw-as.cz/ats-ws/extWs/v1")]
    public partial class extWsLogoutResponseType
    {
        
        private extWsLogoutResponseStatusType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public extWsLogoutResponseStatusType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://agw-as.cz/ats-ws/extWs/v1")]
    public enum extWsLogoutResponseStatusType
    {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        SYSTEM_ERROR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class extWsLogoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="extWsLogoutRequest", Namespace="http://agw-as.cz/ats-ws/extWs/v1", Order=0)]
        public DatovkaSharp.Services.ExtWs.extWsLogoutRequestType extWsLogoutRequest1;
        
        public extWsLogoutRequest()
        {
        }
        
        public extWsLogoutRequest(DatovkaSharp.Services.ExtWs.extWsLogoutRequestType extWsLogoutRequest1)
        {
            this.extWsLogoutRequest1 = extWsLogoutRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class extWsLogoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="extWsLogoutResponse", Namespace="http://agw-as.cz/ats-ws/extWs/v1", Order=0)]
        public DatovkaSharp.Services.ExtWs.extWsLogoutResponseType extWsLogoutResponse1;
        
        public extWsLogoutResponse()
        {
        }
        
        public extWsLogoutResponse(DatovkaSharp.Services.ExtWs.extWsLogoutResponseType extWsLogoutResponse1)
        {
            this.extWsLogoutResponse1 = extWsLogoutResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ExtWsChannel : DatovkaSharp.Services.ExtWs.ExtWs, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ExtWsClient : System.ServiceModel.ClientBase<DatovkaSharp.Services.ExtWs.ExtWs>, DatovkaSharp.Services.ExtWs.ExtWs
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExtWsClient() : 
                base(ExtWsClient.GetDefaultBinding(), ExtWsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ExtWsSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExtWsClient(EndpointConfiguration endpointConfiguration) : 
                base(ExtWsClient.GetBindingForEndpoint(endpointConfiguration), ExtWsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExtWsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExtWsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExtWsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExtWsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExtWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.ExtWs.extWsLogoutResponse> DatovkaSharp.Services.ExtWs.ExtWs.extWsLogoutAsync(DatovkaSharp.Services.ExtWs.extWsLogoutRequest request)
        {
            return base.Channel.extWsLogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.ExtWs.extWsLogoutResponse> extWsLogoutAsync(DatovkaSharp.Services.ExtWs.extWsLogoutRequestType extWsLogoutRequest1)
        {
            DatovkaSharp.Services.ExtWs.extWsLogoutRequest inValue = new DatovkaSharp.Services.ExtWs.extWsLogoutRequest();
            inValue.extWsLogoutRequest1 = extWsLogoutRequest1;
            return ((DatovkaSharp.Services.ExtWs.ExtWs)(this)).extWsLogoutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ExtWsSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ExtWsSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://cert.mojedatovaschranka.cz/asws/extWsEndpoint");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ExtWsClient.GetBindingForEndpoint(EndpointConfiguration.ExtWsSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ExtWsClient.GetEndpointAddress(EndpointConfiguration.ExtWsSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            ExtWsSoap11,
        }
    }
}
