//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatovkaSharp.Services.Operations
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://isds.czechpoint.cz/v20", ConfigurationName="DatovkaSharp.Services.Operations.dmOperationsPortType")]
    public interface dmOperationsPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.CreateMessageResponse> CreateMessageAsync(DatovkaSharp.Services.Operations.CreateMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.MessageDownloadResponse> MessageDownloadAsync(DatovkaSharp.Services.Operations.MessageDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.SignedMessageDownloadResponse> SignedMessageDownloadAsync(DatovkaSharp.Services.Operations.SignedMessageDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.SignedSentMessageDownloadResponse> SignedSentMessageDownloadAsync(DatovkaSharp.Services.Operations.SignedSentMessageDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.DummyOperationResponse> DummyOperationAsync(DatovkaSharp.Services.Operations.DummyOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.CreateMultipleMessageResponse> CreateMultipleMessageAsync(DatovkaSharp.Services.Operations.CreateMultipleMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.AuthenticateMessageResponse> AuthenticateMessageAsync(DatovkaSharp.Services.Operations.AuthenticateMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.ResignISDSDocumentResponse> ResignISDSDocumentAsync(DatovkaSharp.Services.Operations.ResignISDSDocumentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMessageCreateInput
    {
        
        private tMessageCreateInputDmEnvelope dmEnvelopeField;
        
        private tFilesArrayDmFile[] dmFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tMessageCreateInputDmEnvelope dmEnvelope
        {
            get
            {
                return this.dmEnvelopeField;
            }
            set
            {
                this.dmEnvelopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dmFile", IsNullable=false)]
        public tFilesArrayDmFile[] dmFiles
        {
            get
            {
                return this.dmFilesField;
            }
            set
            {
                this.dmFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMessageCreateInputDmEnvelope : tMessageEnvelopeSub
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMessageEnvelopeSub
    {
        
        private string dmSenderOrgUnitField;
        
        private string dmSenderOrgUnitNumField;
        
        private string dbIDRecipientField;
        
        private string dmRecipientOrgUnitField;
        
        private string dmRecipientOrgUnitNumField;
        
        private string dmToHandsField;
        
        private string dmAnnotationField;
        
        private string dmRecipientRefNumberField;
        
        private string dmSenderRefNumberField;
        
        private string dmRecipientIdentField;
        
        private string dmSenderIdentField;
        
        private string dmLegalTitleLawField;
        
        private string dmLegalTitleYearField;
        
        private string dmLegalTitleSectField;
        
        private string dmLegalTitleParField;
        
        private string dmLegalTitlePointField;
        
        private System.Nullable<bool> dmPersonalDeliveryField;
        
        private System.Nullable<bool> dmAllowSubstDeliveryField;
        
        private System.Nullable<bool> dmOVMField;
        
        private bool dmOVMFieldSpecified;
        
        private tMessageEnvelopeSubDmPublishOwnID dmPublishOwnIDField;
        
        private string dmTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string dmSenderOrgUnit
        {
            get
            {
                return this.dmSenderOrgUnitField;
            }
            set
            {
                this.dmSenderOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string dmSenderOrgUnitNum
        {
            get
            {
                return this.dmSenderOrgUnitNumField;
            }
            set
            {
                this.dmSenderOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dbIDRecipient
        {
            get
            {
                return this.dbIDRecipientField;
            }
            set
            {
                this.dbIDRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string dmRecipientOrgUnit
        {
            get
            {
                return this.dmRecipientOrgUnitField;
            }
            set
            {
                this.dmRecipientOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=4)]
        public string dmRecipientOrgUnitNum
        {
            get
            {
                return this.dmRecipientOrgUnitNumField;
            }
            set
            {
                this.dmRecipientOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string dmToHands
        {
            get
            {
                return this.dmToHandsField;
            }
            set
            {
                this.dmToHandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string dmAnnotation
        {
            get
            {
                return this.dmAnnotationField;
            }
            set
            {
                this.dmAnnotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string dmRecipientRefNumber
        {
            get
            {
                return this.dmRecipientRefNumberField;
            }
            set
            {
                this.dmRecipientRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string dmSenderRefNumber
        {
            get
            {
                return this.dmSenderRefNumberField;
            }
            set
            {
                this.dmSenderRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string dmRecipientIdent
        {
            get
            {
                return this.dmRecipientIdentField;
            }
            set
            {
                this.dmRecipientIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string dmSenderIdent
        {
            get
            {
                return this.dmSenderIdentField;
            }
            set
            {
                this.dmSenderIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=11)]
        public string dmLegalTitleLaw
        {
            get
            {
                return this.dmLegalTitleLawField;
            }
            set
            {
                this.dmLegalTitleLawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=12)]
        public string dmLegalTitleYear
        {
            get
            {
                return this.dmLegalTitleYearField;
            }
            set
            {
                this.dmLegalTitleYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string dmLegalTitleSect
        {
            get
            {
                return this.dmLegalTitleSectField;
            }
            set
            {
                this.dmLegalTitleSectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string dmLegalTitlePar
        {
            get
            {
                return this.dmLegalTitleParField;
            }
            set
            {
                this.dmLegalTitleParField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string dmLegalTitlePoint
        {
            get
            {
                return this.dmLegalTitlePointField;
            }
            set
            {
                this.dmLegalTitlePointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<bool> dmPersonalDelivery
        {
            get
            {
                return this.dmPersonalDeliveryField;
            }
            set
            {
                this.dmPersonalDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<bool> dmAllowSubstDelivery
        {
            get
            {
                return this.dmAllowSubstDeliveryField;
            }
            set
            {
                this.dmAllowSubstDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<bool> dmOVM
        {
            get
            {
                return this.dmOVMField;
            }
            set
            {
                this.dmOVMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmOVMSpecified
        {
            get
            {
                return this.dmOVMFieldSpecified;
            }
            set
            {
                this.dmOVMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public tMessageEnvelopeSubDmPublishOwnID dmPublishOwnID
        {
            get
            {
                return this.dmPublishOwnIDField;
            }
            set
            {
                this.dmPublishOwnIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmType
        {
            get
            {
                return this.dmTypeField;
            }
            set
            {
                this.dmTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMessageEnvelopeSubDmPublishOwnID
    {
        
        private string idLevelField;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string IdLevel
        {
            get
            {
                return this.idLevelField;
            }
            set
            {
                this.idLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tResignDocOutput
    {
        
        private byte[] dmResultDocField;
        
        private System.DateTime dmValidToField;
        
        private bool dmValidToFieldSpecified;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] dmResultDoc
        {
            get
            {
                return this.dmResultDocField;
            }
            set
            {
                this.dmResultDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime dmValidTo
        {
            get
            {
                return this.dmValidToField;
            }
            set
            {
                this.dmValidToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmValidToSpecified
        {
            get
            {
                return this.dmValidToFieldSpecified;
            }
            set
            {
                this.dmValidToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tStatus
    {
        
        private string dmStatusCodeField;
        
        private string dmStatusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmStatusCode
        {
            get
            {
                return this.dmStatusCodeField;
            }
            set
            {
                this.dmStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dmStatusMessage
        {
            get
            {
                return this.dmStatusMessageField;
            }
            set
            {
                this.dmStatusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tResignDocInput
    {
        
        private byte[] dmDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmDoc
        {
            get
            {
                return this.dmDocField;
            }
            set
            {
                this.dmDocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tAuthenticateMessageOutput
    {
        
        private System.Nullable<bool> dmAuthResultField;
        
        private bool dmAuthResultFieldSpecified;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> dmAuthResult
        {
            get
            {
                return this.dmAuthResultField;
            }
            set
            {
                this.dmAuthResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmAuthResultSpecified
        {
            get
            {
                return this.dmAuthResultFieldSpecified;
            }
            set
            {
                this.dmAuthResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tAuthenticateMessageInput
    {
        
        private byte[] dmMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmMessage
        {
            get
            {
                return this.dmMessageField;
            }
            set
            {
                this.dmMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMStatus
    {
        
        private string dmIDField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMultipleMessageCreateOutput
    {
        
        private tMStatus[] dmMultipleStatusField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dmSingleStatus")]
        public tMStatus[] dmMultipleStatus
        {
            get
            {
                return this.dmMultipleStatusField;
            }
            set
            {
                this.dmMultipleStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMultipleMessageEnvelopeSub
    {
        
        private string dmSenderOrgUnitField;
        
        private string dmSenderOrgUnitNumField;
        
        private string dmAnnotationField;
        
        private string dmRecipientRefNumberField;
        
        private string dmSenderRefNumberField;
        
        private string dmRecipientIdentField;
        
        private string dmSenderIdentField;
        
        private string dmLegalTitleLawField;
        
        private string dmLegalTitleYearField;
        
        private string dmLegalTitleSectField;
        
        private string dmLegalTitleParField;
        
        private string dmLegalTitlePointField;
        
        private System.Nullable<bool> dmPersonalDeliveryField;
        
        private System.Nullable<bool> dmAllowSubstDeliveryField;
        
        private System.Nullable<bool> dmOVMField;
        
        private bool dmOVMFieldSpecified;
        
        private tMultipleMessageEnvelopeSubDmPublishOwnID dmPublishOwnIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string dmSenderOrgUnit
        {
            get
            {
                return this.dmSenderOrgUnitField;
            }
            set
            {
                this.dmSenderOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string dmSenderOrgUnitNum
        {
            get
            {
                return this.dmSenderOrgUnitNumField;
            }
            set
            {
                this.dmSenderOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dmAnnotation
        {
            get
            {
                return this.dmAnnotationField;
            }
            set
            {
                this.dmAnnotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string dmRecipientRefNumber
        {
            get
            {
                return this.dmRecipientRefNumberField;
            }
            set
            {
                this.dmRecipientRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string dmSenderRefNumber
        {
            get
            {
                return this.dmSenderRefNumberField;
            }
            set
            {
                this.dmSenderRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string dmRecipientIdent
        {
            get
            {
                return this.dmRecipientIdentField;
            }
            set
            {
                this.dmRecipientIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string dmSenderIdent
        {
            get
            {
                return this.dmSenderIdentField;
            }
            set
            {
                this.dmSenderIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=7)]
        public string dmLegalTitleLaw
        {
            get
            {
                return this.dmLegalTitleLawField;
            }
            set
            {
                this.dmLegalTitleLawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=8)]
        public string dmLegalTitleYear
        {
            get
            {
                return this.dmLegalTitleYearField;
            }
            set
            {
                this.dmLegalTitleYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string dmLegalTitleSect
        {
            get
            {
                return this.dmLegalTitleSectField;
            }
            set
            {
                this.dmLegalTitleSectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string dmLegalTitlePar
        {
            get
            {
                return this.dmLegalTitleParField;
            }
            set
            {
                this.dmLegalTitleParField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string dmLegalTitlePoint
        {
            get
            {
                return this.dmLegalTitlePointField;
            }
            set
            {
                this.dmLegalTitlePointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<bool> dmPersonalDelivery
        {
            get
            {
                return this.dmPersonalDeliveryField;
            }
            set
            {
                this.dmPersonalDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> dmAllowSubstDelivery
        {
            get
            {
                return this.dmAllowSubstDeliveryField;
            }
            set
            {
                this.dmAllowSubstDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> dmOVM
        {
            get
            {
                return this.dmOVMField;
            }
            set
            {
                this.dmOVMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmOVMSpecified
        {
            get
            {
                return this.dmOVMFieldSpecified;
            }
            set
            {
                this.dmOVMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public tMultipleMessageEnvelopeSubDmPublishOwnID dmPublishOwnID
        {
            get
            {
                return this.dmPublishOwnIDField;
            }
            set
            {
                this.dmPublishOwnIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMultipleMessageEnvelopeSubDmPublishOwnID
    {
        
        private string idLevelField;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string IdLevel
        {
            get
            {
                return this.idLevelField;
            }
            set
            {
                this.idLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tRecipients
    {
        
        private string dbIDRecipientField;
        
        private string dmRecipientOrgUnitField;
        
        private string dmRecipientOrgUnitNumField;
        
        private string dmToHandsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dbIDRecipient
        {
            get
            {
                return this.dbIDRecipientField;
            }
            set
            {
                this.dbIDRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string dmRecipientOrgUnit
        {
            get
            {
                return this.dmRecipientOrgUnitField;
            }
            set
            {
                this.dmRecipientOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string dmRecipientOrgUnitNum
        {
            get
            {
                return this.dmRecipientOrgUnitNumField;
            }
            set
            {
                this.dmRecipientOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string dmToHands
        {
            get
            {
                return this.dmToHandsField;
            }
            set
            {
                this.dmToHandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMultipleMessageCreateInput
    {
        
        private tRecipients[] dmRecipientsField;
        
        private tMultipleMessageCreateInputDmEnvelope dmEnvelopeField;
        
        private tFilesArrayDmFile[] dmFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dmRecipient", IsNullable=false)]
        public tRecipients[] dmRecipients
        {
            get
            {
                return this.dmRecipientsField;
            }
            set
            {
                this.dmRecipientsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tMultipleMessageCreateInputDmEnvelope dmEnvelope
        {
            get
            {
                return this.dmEnvelopeField;
            }
            set
            {
                this.dmEnvelopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dmFile", IsNullable=false)]
        public tFilesArrayDmFile[] dmFiles
        {
            get
            {
                return this.dmFilesField;
            }
            set
            {
                this.dmFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMultipleMessageCreateInputDmEnvelope : tMultipleMessageEnvelopeSub
    {
        
        private string dmTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmType
        {
            get
            {
                return this.dmTypeField;
            }
            set
            {
                this.dmTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tFilesArrayDmFile : tFile
    {
        
        private string dmMimeTypeField;
        
        private tFilesArrayDmFileDmFileMetaType dmFileMetaTypeField;
        
        private string dmFileGuidField;
        
        private string dmUpFileGuidField;
        
        private string dmFileDescrField;
        
        private string dmFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmMimeType
        {
            get
            {
                return this.dmMimeTypeField;
            }
            set
            {
                this.dmMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tFilesArrayDmFileDmFileMetaType dmFileMetaType
        {
            get
            {
                return this.dmFileMetaTypeField;
            }
            set
            {
                this.dmFileMetaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileGuid
        {
            get
            {
                return this.dmFileGuidField;
            }
            set
            {
                this.dmFileGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmUpFileGuid
        {
            get
            {
                return this.dmUpFileGuidField;
            }
            set
            {
                this.dmUpFileGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileDescr
        {
            get
            {
                return this.dmFileDescrField;
            }
            set
            {
                this.dmFileDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFormat
        {
            get
            {
                return this.dmFormatField;
            }
            set
            {
                this.dmFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public enum tFilesArrayDmFileDmFileMetaType
    {
        
        /// <remarks/>
        main,
        
        /// <remarks/>
        enclosure,
        
        /// <remarks/>
        signature,
        
        /// <remarks/>
        meta,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tFile
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dmEncodedContent", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dmXMLContent", typeof(System.Xml.XmlElement), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tDummyOutput
    {
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tSignedMessDownOutput
    {
        
        private byte[] dmSignatureField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmSignature
        {
            get
            {
                return this.dmSignatureField;
            }
            set
            {
                this.dmSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tHash
    {
        
        private string algorithmField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tReturnedMessage
    {
        
        private tReturnedMessageDmDm dmDmField;
        
        private tHash dmHashField;
        
        private byte[] dmQTimestampField;
        
        private System.Nullable<System.DateTime> dmDeliveryTimeField;
        
        private System.Nullable<System.DateTime> dmAcceptanceTimeField;
        
        private string dmMessageStatusField;
        
        private string dmAttachmentSizeField;
        
        private string dmTypeField;
        
        private string specMessFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tReturnedMessageDmDm dmDm
        {
            get
            {
                return this.dmDmField;
            }
            set
            {
                this.dmDmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tHash dmHash
        {
            get
            {
                return this.dmHashField;
            }
            set
            {
                this.dmHashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=2)]
        public byte[] dmQTimestamp
        {
            get
            {
                return this.dmQTimestampField;
            }
            set
            {
                this.dmQTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> dmDeliveryTime
        {
            get
            {
                return this.dmDeliveryTimeField;
            }
            set
            {
                this.dmDeliveryTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dmAcceptanceTime
        {
            get
            {
                return this.dmAcceptanceTimeField;
            }
            set
            {
                this.dmAcceptanceTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string dmMessageStatus
        {
            get
            {
                return this.dmMessageStatusField;
            }
            set
            {
                this.dmMessageStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=6)]
        public string dmAttachmentSize
        {
            get
            {
                return this.dmAttachmentSizeField;
            }
            set
            {
                this.dmAttachmentSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmType
        {
            get
            {
                return this.dmTypeField;
            }
            set
            {
                this.dmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string specMessFlag
        {
            get
            {
                return this.specMessFlagField;
            }
            set
            {
                this.specMessFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tReturnedMessageDmDm
    {
        
        private string dmIDField;
        
        private string dbIDSenderField;
        
        private string dmSenderField;
        
        private string dmSenderAddressField;
        
        private int dmSenderTypeField;
        
        private string dmRecipientField;
        
        private string dmRecipientAddressField;
        
        private System.Nullable<bool> dmAmbiguousRecipientField;
        
        private bool dmAmbiguousRecipientFieldSpecified;
        
        private string dmSenderOrgUnitField;
        
        private string dmSenderOrgUnitNumField;
        
        private string dbIDRecipientField;
        
        private string dmRecipientOrgUnitField;
        
        private string dmRecipientOrgUnitNumField;
        
        private string dmToHandsField;
        
        private string dmAnnotationField;
        
        private string dmRecipientRefNumberField;
        
        private string dmSenderRefNumberField;
        
        private string dmRecipientIdentField;
        
        private string dmSenderIdentField;
        
        private string dmLegalTitleLawField;
        
        private string dmLegalTitleYearField;
        
        private string dmLegalTitleSectField;
        
        private string dmLegalTitleParField;
        
        private string dmLegalTitlePointField;
        
        private System.Nullable<bool> dmPersonalDeliveryField;
        
        private System.Nullable<bool> dmAllowSubstDeliveryField;
        
        private tFilesArrayDmFile[] dmFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string dbIDSender
        {
            get
            {
                return this.dbIDSenderField;
            }
            set
            {
                this.dbIDSenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dmSender
        {
            get
            {
                return this.dmSenderField;
            }
            set
            {
                this.dmSenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string dmSenderAddress
        {
            get
            {
                return this.dmSenderAddressField;
            }
            set
            {
                this.dmSenderAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int dmSenderType
        {
            get
            {
                return this.dmSenderTypeField;
            }
            set
            {
                this.dmSenderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string dmRecipient
        {
            get
            {
                return this.dmRecipientField;
            }
            set
            {
                this.dmRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string dmRecipientAddress
        {
            get
            {
                return this.dmRecipientAddressField;
            }
            set
            {
                this.dmRecipientAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> dmAmbiguousRecipient
        {
            get
            {
                return this.dmAmbiguousRecipientField;
            }
            set
            {
                this.dmAmbiguousRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmAmbiguousRecipientSpecified
        {
            get
            {
                return this.dmAmbiguousRecipientFieldSpecified;
            }
            set
            {
                this.dmAmbiguousRecipientFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string dmSenderOrgUnit
        {
            get
            {
                return this.dmSenderOrgUnitField;
            }
            set
            {
                this.dmSenderOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=9)]
        public string dmSenderOrgUnitNum
        {
            get
            {
                return this.dmSenderOrgUnitNumField;
            }
            set
            {
                this.dmSenderOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string dbIDRecipient
        {
            get
            {
                return this.dbIDRecipientField;
            }
            set
            {
                this.dbIDRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string dmRecipientOrgUnit
        {
            get
            {
                return this.dmRecipientOrgUnitField;
            }
            set
            {
                this.dmRecipientOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=12)]
        public string dmRecipientOrgUnitNum
        {
            get
            {
                return this.dmRecipientOrgUnitNumField;
            }
            set
            {
                this.dmRecipientOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string dmToHands
        {
            get
            {
                return this.dmToHandsField;
            }
            set
            {
                this.dmToHandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string dmAnnotation
        {
            get
            {
                return this.dmAnnotationField;
            }
            set
            {
                this.dmAnnotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string dmRecipientRefNumber
        {
            get
            {
                return this.dmRecipientRefNumberField;
            }
            set
            {
                this.dmRecipientRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string dmSenderRefNumber
        {
            get
            {
                return this.dmSenderRefNumberField;
            }
            set
            {
                this.dmSenderRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string dmRecipientIdent
        {
            get
            {
                return this.dmRecipientIdentField;
            }
            set
            {
                this.dmRecipientIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string dmSenderIdent
        {
            get
            {
                return this.dmSenderIdentField;
            }
            set
            {
                this.dmSenderIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=19)]
        public string dmLegalTitleLaw
        {
            get
            {
                return this.dmLegalTitleLawField;
            }
            set
            {
                this.dmLegalTitleLawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=20)]
        public string dmLegalTitleYear
        {
            get
            {
                return this.dmLegalTitleYearField;
            }
            set
            {
                this.dmLegalTitleYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string dmLegalTitleSect
        {
            get
            {
                return this.dmLegalTitleSectField;
            }
            set
            {
                this.dmLegalTitleSectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string dmLegalTitlePar
        {
            get
            {
                return this.dmLegalTitleParField;
            }
            set
            {
                this.dmLegalTitleParField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string dmLegalTitlePoint
        {
            get
            {
                return this.dmLegalTitlePointField;
            }
            set
            {
                this.dmLegalTitlePointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<bool> dmPersonalDelivery
        {
            get
            {
                return this.dmPersonalDeliveryField;
            }
            set
            {
                this.dmPersonalDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<bool> dmAllowSubstDelivery
        {
            get
            {
                return this.dmAllowSubstDeliveryField;
            }
            set
            {
                this.dmAllowSubstDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=26)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dmFile", IsNullable=false)]
        public tFilesArrayDmFile[] dmFiles
        {
            get
            {
                return this.dmFilesField;
            }
            set
            {
                this.dmFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMessDownOutput
    {
        
        private tReturnedMessage dmReturnedMessageField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public tReturnedMessage dmReturnedMessage
        {
            get
            {
                return this.dmReturnedMessageField;
            }
            set
            {
                this.dmReturnedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tIDMessInput
    {
        
        private string dmIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tMessageCreateOutput
    {
        
        private string dmIDField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tMessageCreateInput CreateMessage;
        
        public CreateMessageRequest()
        {
        }
        
        public CreateMessageRequest(DatovkaSharp.Services.Operations.tMessageCreateInput CreateMessage)
        {
            this.CreateMessage = CreateMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMessageResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tMessageCreateOutput CreateMessageResponse1;
        
        public CreateMessageResponse()
        {
        }
        
        public CreateMessageResponse(DatovkaSharp.Services.Operations.tMessageCreateOutput CreateMessageResponse1)
        {
            this.CreateMessageResponse1 = CreateMessageResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tIDMessInput MessageDownload;
        
        public MessageDownloadRequest()
        {
        }
        
        public MessageDownloadRequest(DatovkaSharp.Services.Operations.tIDMessInput MessageDownload)
        {
            this.MessageDownload = MessageDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageDownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageDownloadResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tMessDownOutput MessageDownloadResponse1;
        
        public MessageDownloadResponse()
        {
        }
        
        public MessageDownloadResponse(DatovkaSharp.Services.Operations.tMessDownOutput MessageDownloadResponse1)
        {
            this.MessageDownloadResponse1 = MessageDownloadResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignedMessageDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tIDMessInput SignedMessageDownload;
        
        public SignedMessageDownloadRequest()
        {
        }
        
        public SignedMessageDownloadRequest(DatovkaSharp.Services.Operations.tIDMessInput SignedMessageDownload)
        {
            this.SignedMessageDownload = SignedMessageDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignedMessageDownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignedMessageDownloadResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tSignedMessDownOutput SignedMessageDownloadResponse1;
        
        public SignedMessageDownloadResponse()
        {
        }
        
        public SignedMessageDownloadResponse(DatovkaSharp.Services.Operations.tSignedMessDownOutput SignedMessageDownloadResponse1)
        {
            this.SignedMessageDownloadResponse1 = SignedMessageDownloadResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignedSentMessageDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tIDMessInput SignedSentMessageDownload;
        
        public SignedSentMessageDownloadRequest()
        {
        }
        
        public SignedSentMessageDownloadRequest(DatovkaSharp.Services.Operations.tIDMessInput SignedSentMessageDownload)
        {
            this.SignedSentMessageDownload = SignedSentMessageDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignedSentMessageDownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignedSentMessageDownloadResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tSignedMessDownOutput SignedSentMessageDownloadResponse1;
        
        public SignedSentMessageDownloadResponse()
        {
        }
        
        public SignedSentMessageDownloadResponse(DatovkaSharp.Services.Operations.tSignedMessDownOutput SignedSentMessageDownloadResponse1)
        {
            this.SignedSentMessageDownloadResponse1 = SignedSentMessageDownloadResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DummyOperationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DummyOperation;
        
        public DummyOperationRequest()
        {
        }
        
        public DummyOperationRequest(string DummyOperation)
        {
            this.DummyOperation = DummyOperation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DummyOperationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DummyOperationResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tDummyOutput DummyOperationResponse1;
        
        public DummyOperationResponse()
        {
        }
        
        public DummyOperationResponse(DatovkaSharp.Services.Operations.tDummyOutput DummyOperationResponse1)
        {
            this.DummyOperationResponse1 = DummyOperationResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMultipleMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tMultipleMessageCreateInput CreateMultipleMessage;
        
        public CreateMultipleMessageRequest()
        {
        }
        
        public CreateMultipleMessageRequest(DatovkaSharp.Services.Operations.tMultipleMessageCreateInput CreateMultipleMessage)
        {
            this.CreateMultipleMessage = CreateMultipleMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMultipleMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMultipleMessageResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tMultipleMessageCreateOutput CreateMultipleMessageResponse1;
        
        public CreateMultipleMessageResponse()
        {
        }
        
        public CreateMultipleMessageResponse(DatovkaSharp.Services.Operations.tMultipleMessageCreateOutput CreateMultipleMessageResponse1)
        {
            this.CreateMultipleMessageResponse1 = CreateMultipleMessageResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tAuthenticateMessageInput AuthenticateMessage;
        
        public AuthenticateMessageRequest()
        {
        }
        
        public AuthenticateMessageRequest(DatovkaSharp.Services.Operations.tAuthenticateMessageInput AuthenticateMessage)
        {
            this.AuthenticateMessage = AuthenticateMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateMessageResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Operations.tAuthenticateMessageOutput AuthenticateMessageResponse1;
        
        public AuthenticateMessageResponse()
        {
        }
        
        public AuthenticateMessageResponse(DatovkaSharp.Services.Operations.tAuthenticateMessageOutput AuthenticateMessageResponse1)
        {
            this.AuthenticateMessageResponse1 = AuthenticateMessageResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResignISDSDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Re-signISDSDocument", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Re-signISDSDocument")]
        public DatovkaSharp.Services.Operations.tResignDocInput ResignISDSDocument;
        
        public ResignISDSDocumentRequest()
        {
        }
        
        public ResignISDSDocumentRequest(DatovkaSharp.Services.Operations.tResignDocInput ResignISDSDocument)
        {
            this.ResignISDSDocument = ResignISDSDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResignISDSDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Re-signISDSDocumentResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Re-signISDSDocumentResponse")]
        public DatovkaSharp.Services.Operations.tResignDocOutput ResignISDSDocumentResponse1;
        
        public ResignISDSDocumentResponse()
        {
        }
        
        public ResignISDSDocumentResponse(DatovkaSharp.Services.Operations.tResignDocOutput ResignISDSDocumentResponse1)
        {
            this.ResignISDSDocumentResponse1 = ResignISDSDocumentResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface dmOperationsPortTypeChannel : DatovkaSharp.Services.Operations.dmOperationsPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class dmOperationsPortTypeClient : System.ServiceModel.ClientBase<DatovkaSharp.Services.Operations.dmOperationsPortType>, DatovkaSharp.Services.Operations.dmOperationsPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public dmOperationsPortTypeClient() : 
                base(dmOperationsPortTypeClient.GetDefaultBinding(), dmOperationsPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.dmOperationsPortType.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmOperationsPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(dmOperationsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), dmOperationsPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmOperationsPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(dmOperationsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmOperationsPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(dmOperationsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmOperationsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.CreateMessageResponse> DatovkaSharp.Services.Operations.dmOperationsPortType.CreateMessageAsync(DatovkaSharp.Services.Operations.CreateMessageRequest request)
        {
            return base.Channel.CreateMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.CreateMessageResponse> CreateMessageAsync(DatovkaSharp.Services.Operations.tMessageCreateInput CreateMessage)
        {
            DatovkaSharp.Services.Operations.CreateMessageRequest inValue = new DatovkaSharp.Services.Operations.CreateMessageRequest();
            inValue.CreateMessage = CreateMessage;
            return ((DatovkaSharp.Services.Operations.dmOperationsPortType)(this)).CreateMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.MessageDownloadResponse> DatovkaSharp.Services.Operations.dmOperationsPortType.MessageDownloadAsync(DatovkaSharp.Services.Operations.MessageDownloadRequest request)
        {
            return base.Channel.MessageDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.MessageDownloadResponse> MessageDownloadAsync(DatovkaSharp.Services.Operations.tIDMessInput MessageDownload)
        {
            DatovkaSharp.Services.Operations.MessageDownloadRequest inValue = new DatovkaSharp.Services.Operations.MessageDownloadRequest();
            inValue.MessageDownload = MessageDownload;
            return ((DatovkaSharp.Services.Operations.dmOperationsPortType)(this)).MessageDownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.SignedMessageDownloadResponse> DatovkaSharp.Services.Operations.dmOperationsPortType.SignedMessageDownloadAsync(DatovkaSharp.Services.Operations.SignedMessageDownloadRequest request)
        {
            return base.Channel.SignedMessageDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.SignedMessageDownloadResponse> SignedMessageDownloadAsync(DatovkaSharp.Services.Operations.tIDMessInput SignedMessageDownload)
        {
            DatovkaSharp.Services.Operations.SignedMessageDownloadRequest inValue = new DatovkaSharp.Services.Operations.SignedMessageDownloadRequest();
            inValue.SignedMessageDownload = SignedMessageDownload;
            return ((DatovkaSharp.Services.Operations.dmOperationsPortType)(this)).SignedMessageDownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.SignedSentMessageDownloadResponse> DatovkaSharp.Services.Operations.dmOperationsPortType.SignedSentMessageDownloadAsync(DatovkaSharp.Services.Operations.SignedSentMessageDownloadRequest request)
        {
            return base.Channel.SignedSentMessageDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.SignedSentMessageDownloadResponse> SignedSentMessageDownloadAsync(DatovkaSharp.Services.Operations.tIDMessInput SignedSentMessageDownload)
        {
            DatovkaSharp.Services.Operations.SignedSentMessageDownloadRequest inValue = new DatovkaSharp.Services.Operations.SignedSentMessageDownloadRequest();
            inValue.SignedSentMessageDownload = SignedSentMessageDownload;
            return ((DatovkaSharp.Services.Operations.dmOperationsPortType)(this)).SignedSentMessageDownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.DummyOperationResponse> DatovkaSharp.Services.Operations.dmOperationsPortType.DummyOperationAsync(DatovkaSharp.Services.Operations.DummyOperationRequest request)
        {
            return base.Channel.DummyOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.DummyOperationResponse> DummyOperationAsync(string DummyOperation)
        {
            DatovkaSharp.Services.Operations.DummyOperationRequest inValue = new DatovkaSharp.Services.Operations.DummyOperationRequest();
            inValue.DummyOperation = DummyOperation;
            return ((DatovkaSharp.Services.Operations.dmOperationsPortType)(this)).DummyOperationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.CreateMultipleMessageResponse> DatovkaSharp.Services.Operations.dmOperationsPortType.CreateMultipleMessageAsync(DatovkaSharp.Services.Operations.CreateMultipleMessageRequest request)
        {
            return base.Channel.CreateMultipleMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.CreateMultipleMessageResponse> CreateMultipleMessageAsync(DatovkaSharp.Services.Operations.tMultipleMessageCreateInput CreateMultipleMessage)
        {
            DatovkaSharp.Services.Operations.CreateMultipleMessageRequest inValue = new DatovkaSharp.Services.Operations.CreateMultipleMessageRequest();
            inValue.CreateMultipleMessage = CreateMultipleMessage;
            return ((DatovkaSharp.Services.Operations.dmOperationsPortType)(this)).CreateMultipleMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.AuthenticateMessageResponse> DatovkaSharp.Services.Operations.dmOperationsPortType.AuthenticateMessageAsync(DatovkaSharp.Services.Operations.AuthenticateMessageRequest request)
        {
            return base.Channel.AuthenticateMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.AuthenticateMessageResponse> AuthenticateMessageAsync(DatovkaSharp.Services.Operations.tAuthenticateMessageInput AuthenticateMessage)
        {
            DatovkaSharp.Services.Operations.AuthenticateMessageRequest inValue = new DatovkaSharp.Services.Operations.AuthenticateMessageRequest();
            inValue.AuthenticateMessage = AuthenticateMessage;
            return ((DatovkaSharp.Services.Operations.dmOperationsPortType)(this)).AuthenticateMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.ResignISDSDocumentResponse> DatovkaSharp.Services.Operations.dmOperationsPortType.ResignISDSDocumentAsync(DatovkaSharp.Services.Operations.ResignISDSDocumentRequest request)
        {
            return base.Channel.ResignISDSDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Operations.ResignISDSDocumentResponse> ResignISDSDocumentAsync(DatovkaSharp.Services.Operations.tResignDocInput ResignISDSDocument)
        {
            DatovkaSharp.Services.Operations.ResignISDSDocumentRequest inValue = new DatovkaSharp.Services.Operations.ResignISDSDocumentRequest();
            inValue.ResignISDSDocument = ResignISDSDocument;
            return ((DatovkaSharp.Services.Operations.dmOperationsPortType)(this)).ResignISDSDocumentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.dmOperationsPortType))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.dmOperationsPortType))
            {
                return new System.ServiceModel.EndpointAddress("https://ws1.mojedatovaschranka.cz/DS/dz");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return dmOperationsPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.dmOperationsPortType);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return dmOperationsPortTypeClient.GetEndpointAddress(EndpointConfiguration.dmOperationsPortType);
        }
        
        public enum EndpointConfiguration
        {
            
            dmOperationsPortType,
        }
    }
}
