//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatovkaSharp.Services.Access
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://isds.czechpoint.cz/v20", ConfigurationName="DatovkaSharp.Services.Access.DataBoxAccessPortType")]
    public interface DataBoxAccessPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetOwnerInfoFromLoginResponse> GetOwnerInfoFromLoginAsync(DatovkaSharp.Services.Access.GetOwnerInfoFromLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetOwnerInfoFromLogin2Response> GetOwnerInfoFromLogin2Async(DatovkaSharp.Services.Access.GetOwnerInfoFromLogin2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetUserInfoFromLoginResponse> GetUserInfoFromLoginAsync(DatovkaSharp.Services.Access.GetUserInfoFromLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetUserInfoFromLogin2Response> GetUserInfoFromLogin2Async(DatovkaSharp.Services.Access.GetUserInfoFromLogin2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.ChangeISDSPasswordResponse> ChangeISDSPasswordAsync(DatovkaSharp.Services.Access.ChangeISDSPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetPasswordInfoResponse> GetPasswordInfoAsync(DatovkaSharp.Services.Access.GetPasswordInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tDummyInput
    {
        
        private string dbDummyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dbDummy
        {
            get
            {
                return this.dbDummyField;
            }
            set
            {
                this.dbDummyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tGetPasswInfoOutput
    {
        
        private System.Nullable<System.DateTime> pswExpDateField;
        
        private bool pswExpDateFieldSpecified;
        
        private tDbReqStatus dbStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> pswExpDate
        {
            get
            {
                return this.pswExpDateField;
            }
            set
            {
                this.pswExpDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pswExpDateSpecified
        {
            get
            {
                return this.pswExpDateFieldSpecified;
            }
            set
            {
                this.pswExpDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tDbReqStatus dbStatus
        {
            get
            {
                return this.dbStatusField;
            }
            set
            {
                this.dbStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tDbReqStatus
    {
        
        private string dbStatusCodeField;
        
        private string dbStatusMessageField;
        
        private string dbStatusRefNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dbStatusCode
        {
            get
            {
                return this.dbStatusCodeField;
            }
            set
            {
                this.dbStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dbStatusMessage
        {
            get
            {
                return this.dbStatusMessageField;
            }
            set
            {
                this.dbStatusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dbStatusRefNumber
        {
            get
            {
                return this.dbStatusRefNumberField;
            }
            set
            {
                this.dbStatusRefNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tReqStatusOutput
    {
        
        private tDbReqStatus dbStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tDbReqStatus dbStatus
        {
            get
            {
                return this.dbStatusField;
            }
            set
            {
                this.dbStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tChngPasswInput
    {
        
        private string dbOldPasswordField;
        
        private string dbNewPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dbOldPassword
        {
            get
            {
                return this.dbOldPasswordField;
            }
            set
            {
                this.dbOldPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dbNewPassword
        {
            get
            {
                return this.dbNewPasswordField;
            }
            set
            {
                this.dbNewPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tDbUserInfoExt2
    {
        
        private bool aifoIsdsField;
        
        private string pnGivenNamesField;
        
        private string pnLastNameField;
        
        private string adCodeField;
        
        private string adCityField;
        
        private string adDistrictField;
        
        private string adStreetField;
        
        private string adNumberInStreetField;
        
        private string adNumberInMunicipalityField;
        
        private string adZipCodeField;
        
        private string adStateField;
        
        private System.Nullable<System.DateTime> biDateField;
        
        private string isdsIDField;
        
        private System.Nullable<tUserType> userTypeField;
        
        private System.Nullable<long> userPrivilsField;
        
        private string icField;
        
        private string firmNameField;
        
        private string caStreetField;
        
        private string caCityField;
        
        private string caZipCodeField;
        
        private string caStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool aifoIsds
        {
            get
            {
                return this.aifoIsdsField;
            }
            set
            {
                this.aifoIsdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string pnGivenNames
        {
            get
            {
                return this.pnGivenNamesField;
            }
            set
            {
                this.pnGivenNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string pnLastName
        {
            get
            {
                return this.pnLastNameField;
            }
            set
            {
                this.pnLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string adCode
        {
            get
            {
                return this.adCodeField;
            }
            set
            {
                this.adCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string adCity
        {
            get
            {
                return this.adCityField;
            }
            set
            {
                this.adCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string adDistrict
        {
            get
            {
                return this.adDistrictField;
            }
            set
            {
                this.adDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string adStreet
        {
            get
            {
                return this.adStreetField;
            }
            set
            {
                this.adStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string adNumberInStreet
        {
            get
            {
                return this.adNumberInStreetField;
            }
            set
            {
                this.adNumberInStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string adNumberInMunicipality
        {
            get
            {
                return this.adNumberInMunicipalityField;
            }
            set
            {
                this.adNumberInMunicipalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string adZipCode
        {
            get
            {
                return this.adZipCodeField;
            }
            set
            {
                this.adZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string adState
        {
            get
            {
                return this.adStateField;
            }
            set
            {
                this.adStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> biDate
        {
            get
            {
                return this.biDateField;
            }
            set
            {
                this.biDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string isdsID
        {
            get
            {
                return this.isdsIDField;
            }
            set
            {
                this.isdsIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<tUserType> userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<long> userPrivils
        {
            get
            {
                return this.userPrivilsField;
            }
            set
            {
                this.userPrivilsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string ic
        {
            get
            {
                return this.icField;
            }
            set
            {
                this.icField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string firmName
        {
            get
            {
                return this.firmNameField;
            }
            set
            {
                this.firmNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string caStreet
        {
            get
            {
                return this.caStreetField;
            }
            set
            {
                this.caStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string caCity
        {
            get
            {
                return this.caCityField;
            }
            set
            {
                this.caCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string caZipCode
        {
            get
            {
                return this.caZipCodeField;
            }
            set
            {
                this.caZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string caState
        {
            get
            {
                return this.caStateField;
            }
            set
            {
                this.caStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public enum tUserType
    {
        
        /// <remarks/>
        PRIMARY_USER,
        
        /// <remarks/>
        ENTRUSTED_USER,
        
        /// <remarks/>
        ADMINISTRATOR,
        
        /// <remarks/>
        OFFICIAL,
        
        /// <remarks/>
        OFFICIAL_CERT,
        
        /// <remarks/>
        LIQUIDATOR,
        
        /// <remarks/>
        RECEIVER,
        
        /// <remarks/>
        GUARDIAN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tGetUserInfoOutput2
    {
        
        private tDbUserInfoExt2 dbUserInfoField;
        
        private tDbReqStatus dbStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tDbUserInfoExt2 dbUserInfo
        {
            get
            {
                return this.dbUserInfoField;
            }
            set
            {
                this.dbUserInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tDbReqStatus dbStatus
        {
            get
            {
                return this.dbStatusField;
            }
            set
            {
                this.dbStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tDbUserInfo
    {
        
        private string pnFirstNameField;
        
        private string pnMiddleNameField;
        
        private string pnLastNameField;
        
        private string pnLastNameAtBirthField;
        
        private string adCityField;
        
        private string adStreetField;
        
        private string adNumberInStreetField;
        
        private string adNumberInMunicipalityField;
        
        private string adZipCodeField;
        
        private string adStateField;
        
        private System.Nullable<System.DateTime> biDateField;
        
        private string userIDField;
        
        private System.Nullable<tUserType> userTypeField;
        
        private System.Nullable<long> userPrivilsField;
        
        private string icField;
        
        private string firmNameField;
        
        private string caStreetField;
        
        private string caCityField;
        
        private string caZipCodeField;
        
        private string caStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string pnFirstName
        {
            get
            {
                return this.pnFirstNameField;
            }
            set
            {
                this.pnFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string pnMiddleName
        {
            get
            {
                return this.pnMiddleNameField;
            }
            set
            {
                this.pnMiddleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string pnLastName
        {
            get
            {
                return this.pnLastNameField;
            }
            set
            {
                this.pnLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string pnLastNameAtBirth
        {
            get
            {
                return this.pnLastNameAtBirthField;
            }
            set
            {
                this.pnLastNameAtBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string adCity
        {
            get
            {
                return this.adCityField;
            }
            set
            {
                this.adCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string adStreet
        {
            get
            {
                return this.adStreetField;
            }
            set
            {
                this.adStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string adNumberInStreet
        {
            get
            {
                return this.adNumberInStreetField;
            }
            set
            {
                this.adNumberInStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string adNumberInMunicipality
        {
            get
            {
                return this.adNumberInMunicipalityField;
            }
            set
            {
                this.adNumberInMunicipalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string adZipCode
        {
            get
            {
                return this.adZipCodeField;
            }
            set
            {
                this.adZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string adState
        {
            get
            {
                return this.adStateField;
            }
            set
            {
                this.adStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> biDate
        {
            get
            {
                return this.biDateField;
            }
            set
            {
                this.biDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<tUserType> userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> userPrivils
        {
            get
            {
                return this.userPrivilsField;
            }
            set
            {
                this.userPrivilsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string ic
        {
            get
            {
                return this.icField;
            }
            set
            {
                this.icField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string firmName
        {
            get
            {
                return this.firmNameField;
            }
            set
            {
                this.firmNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string caStreet
        {
            get
            {
                return this.caStreetField;
            }
            set
            {
                this.caStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string caCity
        {
            get
            {
                return this.caCityField;
            }
            set
            {
                this.caCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string caZipCode
        {
            get
            {
                return this.caZipCodeField;
            }
            set
            {
                this.caZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string caState
        {
            get
            {
                return this.caStateField;
            }
            set
            {
                this.caStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tGetUserInfoOutput
    {
        
        private tDbUserInfo dbUserInfoField;
        
        private tDbReqStatus dbStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tDbUserInfo dbUserInfo
        {
            get
            {
                return this.dbUserInfoField;
            }
            set
            {
                this.dbUserInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tDbReqStatus dbStatus
        {
            get
            {
                return this.dbStatusField;
            }
            set
            {
                this.dbStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tDbOwnerInfoExt2
    {
        
        private string dbIDField;
        
        private System.Nullable<bool> aifoIsdsField;
        
        private bool aifoIsdsFieldSpecified;
        
        private System.Nullable<tDbType> dbTypeField;
        
        private string icField;
        
        private string pnGivenNamesField;
        
        private string pnLastNameField;
        
        private string firmNameField;
        
        private System.Nullable<System.DateTime> biDateField;
        
        private string biCityField;
        
        private string biCountyField;
        
        private string biStateField;
        
        private string adCodeField;
        
        private string adCityField;
        
        private string adDistrictField;
        
        private string adStreetField;
        
        private string adNumberInStreetField;
        
        private string adNumberInMunicipalityField;
        
        private string adZipCodeField;
        
        private string adStateField;
        
        private string nationalityField;
        
        private string dbIdOVMField;
        
        private string dbStateField;
        
        private System.Nullable<bool> dbOpenAddressingField;
        
        private string dbUpperIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string dbID
        {
            get
            {
                return this.dbIDField;
            }
            set
            {
                this.dbIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> aifoIsds
        {
            get
            {
                return this.aifoIsdsField;
            }
            set
            {
                this.aifoIsdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aifoIsdsSpecified
        {
            get
            {
                return this.aifoIsdsFieldSpecified;
            }
            set
            {
                this.aifoIsdsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<tDbType> dbType
        {
            get
            {
                return this.dbTypeField;
            }
            set
            {
                this.dbTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string ic
        {
            get
            {
                return this.icField;
            }
            set
            {
                this.icField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string pnGivenNames
        {
            get
            {
                return this.pnGivenNamesField;
            }
            set
            {
                this.pnGivenNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string pnLastName
        {
            get
            {
                return this.pnLastNameField;
            }
            set
            {
                this.pnLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string firmName
        {
            get
            {
                return this.firmNameField;
            }
            set
            {
                this.firmNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> biDate
        {
            get
            {
                return this.biDateField;
            }
            set
            {
                this.biDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string biCity
        {
            get
            {
                return this.biCityField;
            }
            set
            {
                this.biCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string biCounty
        {
            get
            {
                return this.biCountyField;
            }
            set
            {
                this.biCountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string biState
        {
            get
            {
                return this.biStateField;
            }
            set
            {
                this.biStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string adCode
        {
            get
            {
                return this.adCodeField;
            }
            set
            {
                this.adCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string adCity
        {
            get
            {
                return this.adCityField;
            }
            set
            {
                this.adCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string adDistrict
        {
            get
            {
                return this.adDistrictField;
            }
            set
            {
                this.adDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string adStreet
        {
            get
            {
                return this.adStreetField;
            }
            set
            {
                this.adStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string adNumberInStreet
        {
            get
            {
                return this.adNumberInStreetField;
            }
            set
            {
                this.adNumberInStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string adNumberInMunicipality
        {
            get
            {
                return this.adNumberInMunicipalityField;
            }
            set
            {
                this.adNumberInMunicipalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string adZipCode
        {
            get
            {
                return this.adZipCodeField;
            }
            set
            {
                this.adZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string adState
        {
            get
            {
                return this.adStateField;
            }
            set
            {
                this.adStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string dbIdOVM
        {
            get
            {
                return this.dbIdOVMField;
            }
            set
            {
                this.dbIdOVMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=21)]
        public string dbState
        {
            get
            {
                return this.dbStateField;
            }
            set
            {
                this.dbStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<bool> dbOpenAddressing
        {
            get
            {
                return this.dbOpenAddressingField;
            }
            set
            {
                this.dbOpenAddressingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string dbUpperID
        {
            get
            {
                return this.dbUpperIDField;
            }
            set
            {
                this.dbUpperIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public enum tDbType
    {
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        PFO,
        
        /// <remarks/>
        PFO_REQ,
        
        /// <remarks/>
        PFO_ADVOK,
        
        /// <remarks/>
        PFO_DANPOR,
        
        /// <remarks/>
        PFO_INSSPR,
        
        /// <remarks/>
        PFO_AUDITOR,
        
        /// <remarks/>
        PFO_ZNALEC,
        
        /// <remarks/>
        PFO_TLUMOCNIK,
        
        /// <remarks/>
        PFO_ARCH,
        
        /// <remarks/>
        PFO_AIAT,
        
        /// <remarks/>
        PFO_AZI,
        
        /// <remarks/>
        PO,
        
        /// <remarks/>
        PO_ZAK,
        
        /// <remarks/>
        PO_REQ,
        
        /// <remarks/>
        OVM,
        
        /// <remarks/>
        OVM_NOTAR,
        
        /// <remarks/>
        OVM_EXEKUT,
        
        /// <remarks/>
        OVM_REQ,
        
        /// <remarks/>
        OVM_FO,
        
        /// <remarks/>
        OVM_PFO,
        
        /// <remarks/>
        OVM_PO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tGetOwnInfoOutput2
    {
        
        private tDbOwnerInfoExt2 dbOwnerInfoField;
        
        private tDbReqStatus dbStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tDbOwnerInfoExt2 dbOwnerInfo
        {
            get
            {
                return this.dbOwnerInfoField;
            }
            set
            {
                this.dbOwnerInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tDbReqStatus dbStatus
        {
            get
            {
                return this.dbStatusField;
            }
            set
            {
                this.dbStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tDbOwnerInfo
    {
        
        private string dbIDField;
        
        private System.Nullable<tDbType> dbTypeField;
        
        private string icField;
        
        private string pnFirstNameField;
        
        private string pnMiddleNameField;
        
        private string pnLastNameField;
        
        private string pnLastNameAtBirthField;
        
        private string firmNameField;
        
        private System.Nullable<System.DateTime> biDateField;
        
        private string biCityField;
        
        private string biCountyField;
        
        private string biStateField;
        
        private string adCityField;
        
        private string adStreetField;
        
        private string adNumberInStreetField;
        
        private string adNumberInMunicipalityField;
        
        private string adZipCodeField;
        
        private string adStateField;
        
        private string nationalityField;
        
        private string emailField;
        
        private string telNumberField;
        
        private string identifierField;
        
        private string registryCodeField;
        
        private string dbStateField;
        
        private System.Nullable<bool> dbEffectiveOVMField;
        
        private System.Nullable<bool> dbOpenAddressingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string dbID
        {
            get
            {
                return this.dbIDField;
            }
            set
            {
                this.dbIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<tDbType> dbType
        {
            get
            {
                return this.dbTypeField;
            }
            set
            {
                this.dbTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ic
        {
            get
            {
                return this.icField;
            }
            set
            {
                this.icField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string pnFirstName
        {
            get
            {
                return this.pnFirstNameField;
            }
            set
            {
                this.pnFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string pnMiddleName
        {
            get
            {
                return this.pnMiddleNameField;
            }
            set
            {
                this.pnMiddleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string pnLastName
        {
            get
            {
                return this.pnLastNameField;
            }
            set
            {
                this.pnLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string pnLastNameAtBirth
        {
            get
            {
                return this.pnLastNameAtBirthField;
            }
            set
            {
                this.pnLastNameAtBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string firmName
        {
            get
            {
                return this.firmNameField;
            }
            set
            {
                this.firmNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> biDate
        {
            get
            {
                return this.biDateField;
            }
            set
            {
                this.biDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string biCity
        {
            get
            {
                return this.biCityField;
            }
            set
            {
                this.biCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string biCounty
        {
            get
            {
                return this.biCountyField;
            }
            set
            {
                this.biCountyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string biState
        {
            get
            {
                return this.biStateField;
            }
            set
            {
                this.biStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string adCity
        {
            get
            {
                return this.adCityField;
            }
            set
            {
                this.adCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string adStreet
        {
            get
            {
                return this.adStreetField;
            }
            set
            {
                this.adStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string adNumberInStreet
        {
            get
            {
                return this.adNumberInStreetField;
            }
            set
            {
                this.adNumberInStreetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string adNumberInMunicipality
        {
            get
            {
                return this.adNumberInMunicipalityField;
            }
            set
            {
                this.adNumberInMunicipalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string adZipCode
        {
            get
            {
                return this.adZipCodeField;
            }
            set
            {
                this.adZipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string adState
        {
            get
            {
                return this.adStateField;
            }
            set
            {
                this.adStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string nationality
        {
            get
            {
                return this.nationalityField;
            }
            set
            {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string telNumber
        {
            get
            {
                return this.telNumberField;
            }
            set
            {
                this.telNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string registryCode
        {
            get
            {
                return this.registryCodeField;
            }
            set
            {
                this.registryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=23)]
        public string dbState
        {
            get
            {
                return this.dbStateField;
            }
            set
            {
                this.dbStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<bool> dbEffectiveOVM
        {
            get
            {
                return this.dbEffectiveOVMField;
            }
            set
            {
                this.dbEffectiveOVMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<bool> dbOpenAddressing
        {
            get
            {
                return this.dbOpenAddressingField;
            }
            set
            {
                this.dbOpenAddressingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tGetOwnInfoOutput
    {
        
        private tDbOwnerInfo dbOwnerInfoField;
        
        private tDbReqStatus dbStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tDbOwnerInfo dbOwnerInfo
        {
            get
            {
                return this.dbOwnerInfoField;
            }
            set
            {
                this.dbOwnerInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tDbReqStatus dbStatus
        {
            get
            {
                return this.dbStatusField;
            }
            set
            {
                this.dbStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOwnerInfoFromLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tDummyInput GetOwnerInfoFromLogin;
        
        public GetOwnerInfoFromLoginRequest()
        {
        }
        
        public GetOwnerInfoFromLoginRequest(DatovkaSharp.Services.Access.tDummyInput GetOwnerInfoFromLogin)
        {
            this.GetOwnerInfoFromLogin = GetOwnerInfoFromLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOwnerInfoFromLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOwnerInfoFromLoginResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tGetOwnInfoOutput GetOwnerInfoFromLoginResponse1;
        
        public GetOwnerInfoFromLoginResponse()
        {
        }
        
        public GetOwnerInfoFromLoginResponse(DatovkaSharp.Services.Access.tGetOwnInfoOutput GetOwnerInfoFromLoginResponse1)
        {
            this.GetOwnerInfoFromLoginResponse1 = GetOwnerInfoFromLoginResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOwnerInfoFromLogin2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tDummyInput GetOwnerInfoFromLogin2;
        
        public GetOwnerInfoFromLogin2Request()
        {
        }
        
        public GetOwnerInfoFromLogin2Request(DatovkaSharp.Services.Access.tDummyInput GetOwnerInfoFromLogin2)
        {
            this.GetOwnerInfoFromLogin2 = GetOwnerInfoFromLogin2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOwnerInfoFromLogin2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOwnerInfoFromLogin2Response", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tGetOwnInfoOutput2 GetOwnerInfoFromLogin2Response1;
        
        public GetOwnerInfoFromLogin2Response()
        {
        }
        
        public GetOwnerInfoFromLogin2Response(DatovkaSharp.Services.Access.tGetOwnInfoOutput2 GetOwnerInfoFromLogin2Response1)
        {
            this.GetOwnerInfoFromLogin2Response1 = GetOwnerInfoFromLogin2Response1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoFromLoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tDummyInput GetUserInfoFromLogin;
        
        public GetUserInfoFromLoginRequest()
        {
        }
        
        public GetUserInfoFromLoginRequest(DatovkaSharp.Services.Access.tDummyInput GetUserInfoFromLogin)
        {
            this.GetUserInfoFromLogin = GetUserInfoFromLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoFromLoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoFromLoginResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tGetUserInfoOutput GetUserInfoFromLoginResponse1;
        
        public GetUserInfoFromLoginResponse()
        {
        }
        
        public GetUserInfoFromLoginResponse(DatovkaSharp.Services.Access.tGetUserInfoOutput GetUserInfoFromLoginResponse1)
        {
            this.GetUserInfoFromLoginResponse1 = GetUserInfoFromLoginResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoFromLogin2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tDummyInput GetUserInfoFromLogin2;
        
        public GetUserInfoFromLogin2Request()
        {
        }
        
        public GetUserInfoFromLogin2Request(DatovkaSharp.Services.Access.tDummyInput GetUserInfoFromLogin2)
        {
            this.GetUserInfoFromLogin2 = GetUserInfoFromLogin2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoFromLogin2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoFromLogin2Response", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tGetUserInfoOutput2 GetUserInfoFromLogin2Response1;
        
        public GetUserInfoFromLogin2Response()
        {
        }
        
        public GetUserInfoFromLogin2Response(DatovkaSharp.Services.Access.tGetUserInfoOutput2 GetUserInfoFromLogin2Response1)
        {
            this.GetUserInfoFromLogin2Response1 = GetUserInfoFromLogin2Response1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeISDSPasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tChngPasswInput ChangeISDSPassword;
        
        public ChangeISDSPasswordRequest()
        {
        }
        
        public ChangeISDSPasswordRequest(DatovkaSharp.Services.Access.tChngPasswInput ChangeISDSPassword)
        {
            this.ChangeISDSPassword = ChangeISDSPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeISDSPasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeISDSPasswordResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tReqStatusOutput ChangeISDSPasswordResponse1;
        
        public ChangeISDSPasswordResponse()
        {
        }
        
        public ChangeISDSPasswordResponse(DatovkaSharp.Services.Access.tReqStatusOutput ChangeISDSPasswordResponse1)
        {
            this.ChangeISDSPasswordResponse1 = ChangeISDSPasswordResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPasswordInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tDummyInput GetPasswordInfo;
        
        public GetPasswordInfoRequest()
        {
        }
        
        public GetPasswordInfoRequest(DatovkaSharp.Services.Access.tDummyInput GetPasswordInfo)
        {
            this.GetPasswordInfo = GetPasswordInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPasswordInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPasswordInfoResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Access.tGetPasswInfoOutput GetPasswordInfoResponse1;
        
        public GetPasswordInfoResponse()
        {
        }
        
        public GetPasswordInfoResponse(DatovkaSharp.Services.Access.tGetPasswInfoOutput GetPasswordInfoResponse1)
        {
            this.GetPasswordInfoResponse1 = GetPasswordInfoResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface DataBoxAccessPortTypeChannel : DatovkaSharp.Services.Access.DataBoxAccessPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class DataBoxAccessPortTypeClient : System.ServiceModel.ClientBase<DatovkaSharp.Services.Access.DataBoxAccessPortType>, DatovkaSharp.Services.Access.DataBoxAccessPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataBoxAccessPortTypeClient() : 
                base(DataBoxAccessPortTypeClient.GetDefaultBinding(), DataBoxAccessPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataBoxAccessPortType.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataBoxAccessPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(DataBoxAccessPortTypeClient.GetBindingForEndpoint(endpointConfiguration), DataBoxAccessPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataBoxAccessPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataBoxAccessPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataBoxAccessPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataBoxAccessPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataBoxAccessPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetOwnerInfoFromLoginResponse> DatovkaSharp.Services.Access.DataBoxAccessPortType.GetOwnerInfoFromLoginAsync(DatovkaSharp.Services.Access.GetOwnerInfoFromLoginRequest request)
        {
            return base.Channel.GetOwnerInfoFromLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetOwnerInfoFromLoginResponse> GetOwnerInfoFromLoginAsync(DatovkaSharp.Services.Access.tDummyInput GetOwnerInfoFromLogin)
        {
            DatovkaSharp.Services.Access.GetOwnerInfoFromLoginRequest inValue = new DatovkaSharp.Services.Access.GetOwnerInfoFromLoginRequest();
            inValue.GetOwnerInfoFromLogin = GetOwnerInfoFromLogin;
            return ((DatovkaSharp.Services.Access.DataBoxAccessPortType)(this)).GetOwnerInfoFromLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetOwnerInfoFromLogin2Response> DatovkaSharp.Services.Access.DataBoxAccessPortType.GetOwnerInfoFromLogin2Async(DatovkaSharp.Services.Access.GetOwnerInfoFromLogin2Request request)
        {
            return base.Channel.GetOwnerInfoFromLogin2Async(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetOwnerInfoFromLogin2Response> GetOwnerInfoFromLogin2Async(DatovkaSharp.Services.Access.tDummyInput GetOwnerInfoFromLogin2)
        {
            DatovkaSharp.Services.Access.GetOwnerInfoFromLogin2Request inValue = new DatovkaSharp.Services.Access.GetOwnerInfoFromLogin2Request();
            inValue.GetOwnerInfoFromLogin2 = GetOwnerInfoFromLogin2;
            return ((DatovkaSharp.Services.Access.DataBoxAccessPortType)(this)).GetOwnerInfoFromLogin2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetUserInfoFromLoginResponse> DatovkaSharp.Services.Access.DataBoxAccessPortType.GetUserInfoFromLoginAsync(DatovkaSharp.Services.Access.GetUserInfoFromLoginRequest request)
        {
            return base.Channel.GetUserInfoFromLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetUserInfoFromLoginResponse> GetUserInfoFromLoginAsync(DatovkaSharp.Services.Access.tDummyInput GetUserInfoFromLogin)
        {
            DatovkaSharp.Services.Access.GetUserInfoFromLoginRequest inValue = new DatovkaSharp.Services.Access.GetUserInfoFromLoginRequest();
            inValue.GetUserInfoFromLogin = GetUserInfoFromLogin;
            return ((DatovkaSharp.Services.Access.DataBoxAccessPortType)(this)).GetUserInfoFromLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetUserInfoFromLogin2Response> DatovkaSharp.Services.Access.DataBoxAccessPortType.GetUserInfoFromLogin2Async(DatovkaSharp.Services.Access.GetUserInfoFromLogin2Request request)
        {
            return base.Channel.GetUserInfoFromLogin2Async(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetUserInfoFromLogin2Response> GetUserInfoFromLogin2Async(DatovkaSharp.Services.Access.tDummyInput GetUserInfoFromLogin2)
        {
            DatovkaSharp.Services.Access.GetUserInfoFromLogin2Request inValue = new DatovkaSharp.Services.Access.GetUserInfoFromLogin2Request();
            inValue.GetUserInfoFromLogin2 = GetUserInfoFromLogin2;
            return ((DatovkaSharp.Services.Access.DataBoxAccessPortType)(this)).GetUserInfoFromLogin2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.ChangeISDSPasswordResponse> DatovkaSharp.Services.Access.DataBoxAccessPortType.ChangeISDSPasswordAsync(DatovkaSharp.Services.Access.ChangeISDSPasswordRequest request)
        {
            return base.Channel.ChangeISDSPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Access.ChangeISDSPasswordResponse> ChangeISDSPasswordAsync(DatovkaSharp.Services.Access.tChngPasswInput ChangeISDSPassword)
        {
            DatovkaSharp.Services.Access.ChangeISDSPasswordRequest inValue = new DatovkaSharp.Services.Access.ChangeISDSPasswordRequest();
            inValue.ChangeISDSPassword = ChangeISDSPassword;
            return ((DatovkaSharp.Services.Access.DataBoxAccessPortType)(this)).ChangeISDSPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetPasswordInfoResponse> DatovkaSharp.Services.Access.DataBoxAccessPortType.GetPasswordInfoAsync(DatovkaSharp.Services.Access.GetPasswordInfoRequest request)
        {
            return base.Channel.GetPasswordInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Access.GetPasswordInfoResponse> GetPasswordInfoAsync(DatovkaSharp.Services.Access.tDummyInput GetPasswordInfo)
        {
            DatovkaSharp.Services.Access.GetPasswordInfoRequest inValue = new DatovkaSharp.Services.Access.GetPasswordInfoRequest();
            inValue.GetPasswordInfo = GetPasswordInfo;
            return ((DatovkaSharp.Services.Access.DataBoxAccessPortType)(this)).GetPasswordInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataBoxAccessPortType))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataBoxAccessPortType))
            {
                return new System.ServiceModel.EndpointAddress("https://ws1.mojedatovaschranka.cz/DS/DsManage");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataBoxAccessPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.DataBoxAccessPortType);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataBoxAccessPortTypeClient.GetEndpointAddress(EndpointConfiguration.DataBoxAccessPortType);
        }
        
        public enum EndpointConfiguration
        {
            
            DataBoxAccessPortType,
        }
    }
}
