//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatovkaSharp.Services.Concept
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept", ConfigurationName="DatovkaSharp.Services.Concept.SetConcept")]
    public interface SetConcept
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="SetConcept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Concept.SetConceptResponse> SetConceptAsync(DatovkaSharp.Services.Concept.SetConcept1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SetMultipleConcept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMultipleMessageEnvelopeSub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tMessageEnvelopeSub))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Concept.SetMultipleConceptResponse> SetMultipleConceptAsync(DatovkaSharp.Services.Concept.SetMultipleConcept request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tSetConceptInput
    {
        
        private tSetConceptInputDmEnvelope dmEnvelopeField;
        
        private tFilesArrayDmFile[] dmFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tSetConceptInputDmEnvelope dmEnvelope
        {
            get
            {
                return this.dmEnvelopeField;
            }
            set
            {
                this.dmEnvelopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dmFile", IsNullable=false)]
        public tFilesArrayDmFile[] dmFiles
        {
            get
            {
                return this.dmFilesField;
            }
            set
            {
                this.dmFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tSetConceptInputDmEnvelope : tMessageEnvelopeSub
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tMessageEnvelopeSub
    {
        
        private string dmSenderOrgUnitField;
        
        private string dmSenderOrgUnitNumField;
        
        private string dbIDRecipientField;
        
        private string dmRecipientOrgUnitField;
        
        private string dmRecipientOrgUnitNumField;
        
        private string dmToHandsField;
        
        private string dmAnnotationField;
        
        private string dmRecipientRefNumberField;
        
        private string dmSenderRefNumberField;
        
        private string dmRecipientIdentField;
        
        private string dmSenderIdentField;
        
        private string dmLegalTitleLawField;
        
        private string dmLegalTitleYearField;
        
        private string dmLegalTitleSectField;
        
        private string dmLegalTitleParField;
        
        private string dmLegalTitlePointField;
        
        private System.Nullable<bool> dmPersonalDeliveryField;
        
        private System.Nullable<bool> dmAllowSubstDeliveryField;
        
        private System.Nullable<bool> dmOVMField;
        
        private bool dmOVMFieldSpecified;
        
        private System.Nullable<bool> dmPublishOwnIDField;
        
        private bool dmPublishOwnIDFieldSpecified;
        
        private string dmTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string dmSenderOrgUnit
        {
            get
            {
                return this.dmSenderOrgUnitField;
            }
            set
            {
                this.dmSenderOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string dmSenderOrgUnitNum
        {
            get
            {
                return this.dmSenderOrgUnitNumField;
            }
            set
            {
                this.dmSenderOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dbIDRecipient
        {
            get
            {
                return this.dbIDRecipientField;
            }
            set
            {
                this.dbIDRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string dmRecipientOrgUnit
        {
            get
            {
                return this.dmRecipientOrgUnitField;
            }
            set
            {
                this.dmRecipientOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=4)]
        public string dmRecipientOrgUnitNum
        {
            get
            {
                return this.dmRecipientOrgUnitNumField;
            }
            set
            {
                this.dmRecipientOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string dmToHands
        {
            get
            {
                return this.dmToHandsField;
            }
            set
            {
                this.dmToHandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string dmAnnotation
        {
            get
            {
                return this.dmAnnotationField;
            }
            set
            {
                this.dmAnnotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string dmRecipientRefNumber
        {
            get
            {
                return this.dmRecipientRefNumberField;
            }
            set
            {
                this.dmRecipientRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string dmSenderRefNumber
        {
            get
            {
                return this.dmSenderRefNumberField;
            }
            set
            {
                this.dmSenderRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string dmRecipientIdent
        {
            get
            {
                return this.dmRecipientIdentField;
            }
            set
            {
                this.dmRecipientIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string dmSenderIdent
        {
            get
            {
                return this.dmSenderIdentField;
            }
            set
            {
                this.dmSenderIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=11)]
        public string dmLegalTitleLaw
        {
            get
            {
                return this.dmLegalTitleLawField;
            }
            set
            {
                this.dmLegalTitleLawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=12)]
        public string dmLegalTitleYear
        {
            get
            {
                return this.dmLegalTitleYearField;
            }
            set
            {
                this.dmLegalTitleYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string dmLegalTitleSect
        {
            get
            {
                return this.dmLegalTitleSectField;
            }
            set
            {
                this.dmLegalTitleSectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string dmLegalTitlePar
        {
            get
            {
                return this.dmLegalTitleParField;
            }
            set
            {
                this.dmLegalTitleParField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string dmLegalTitlePoint
        {
            get
            {
                return this.dmLegalTitlePointField;
            }
            set
            {
                this.dmLegalTitlePointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<bool> dmPersonalDelivery
        {
            get
            {
                return this.dmPersonalDeliveryField;
            }
            set
            {
                this.dmPersonalDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<bool> dmAllowSubstDelivery
        {
            get
            {
                return this.dmAllowSubstDeliveryField;
            }
            set
            {
                this.dmAllowSubstDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<bool> dmOVM
        {
            get
            {
                return this.dmOVMField;
            }
            set
            {
                this.dmOVMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmOVMSpecified
        {
            get
            {
                return this.dmOVMFieldSpecified;
            }
            set
            {
                this.dmOVMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<bool> dmPublishOwnID
        {
            get
            {
                return this.dmPublishOwnIDField;
            }
            set
            {
                this.dmPublishOwnIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmPublishOwnIDSpecified
        {
            get
            {
                return this.dmPublishOwnIDFieldSpecified;
            }
            set
            {
                this.dmPublishOwnIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmType
        {
            get
            {
                return this.dmTypeField;
            }
            set
            {
                this.dmTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tSetMultipleConceptOutput
    {
        
        private string dmIDField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tStatus
    {
        
        private string dmStatusCodeField;
        
        private string dmStatusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmStatusCode
        {
            get
            {
                return this.dmStatusCodeField;
            }
            set
            {
                this.dmStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dmStatusMessage
        {
            get
            {
                return this.dmStatusMessageField;
            }
            set
            {
                this.dmStatusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tMultipleMessageEnvelopeSub
    {
        
        private string dmSenderOrgUnitField;
        
        private string dmSenderOrgUnitNumField;
        
        private string dmAnnotationField;
        
        private string dmRecipientRefNumberField;
        
        private string dmSenderRefNumberField;
        
        private string dmRecipientIdentField;
        
        private string dmSenderIdentField;
        
        private string dmLegalTitleLawField;
        
        private string dmLegalTitleYearField;
        
        private string dmLegalTitleSectField;
        
        private string dmLegalTitleParField;
        
        private string dmLegalTitlePointField;
        
        private System.Nullable<bool> dmPersonalDeliveryField;
        
        private System.Nullable<bool> dmAllowSubstDeliveryField;
        
        private System.Nullable<bool> dmOVMField;
        
        private bool dmOVMFieldSpecified;
        
        private System.Nullable<bool> dmPublishOwnIDField;
        
        private bool dmPublishOwnIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string dmSenderOrgUnit
        {
            get
            {
                return this.dmSenderOrgUnitField;
            }
            set
            {
                this.dmSenderOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string dmSenderOrgUnitNum
        {
            get
            {
                return this.dmSenderOrgUnitNumField;
            }
            set
            {
                this.dmSenderOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dmAnnotation
        {
            get
            {
                return this.dmAnnotationField;
            }
            set
            {
                this.dmAnnotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string dmRecipientRefNumber
        {
            get
            {
                return this.dmRecipientRefNumberField;
            }
            set
            {
                this.dmRecipientRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string dmSenderRefNumber
        {
            get
            {
                return this.dmSenderRefNumberField;
            }
            set
            {
                this.dmSenderRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string dmRecipientIdent
        {
            get
            {
                return this.dmRecipientIdentField;
            }
            set
            {
                this.dmRecipientIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string dmSenderIdent
        {
            get
            {
                return this.dmSenderIdentField;
            }
            set
            {
                this.dmSenderIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=7)]
        public string dmLegalTitleLaw
        {
            get
            {
                return this.dmLegalTitleLawField;
            }
            set
            {
                this.dmLegalTitleLawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=8)]
        public string dmLegalTitleYear
        {
            get
            {
                return this.dmLegalTitleYearField;
            }
            set
            {
                this.dmLegalTitleYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string dmLegalTitleSect
        {
            get
            {
                return this.dmLegalTitleSectField;
            }
            set
            {
                this.dmLegalTitleSectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string dmLegalTitlePar
        {
            get
            {
                return this.dmLegalTitleParField;
            }
            set
            {
                this.dmLegalTitleParField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string dmLegalTitlePoint
        {
            get
            {
                return this.dmLegalTitlePointField;
            }
            set
            {
                this.dmLegalTitlePointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<bool> dmPersonalDelivery
        {
            get
            {
                return this.dmPersonalDeliveryField;
            }
            set
            {
                this.dmPersonalDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<bool> dmAllowSubstDelivery
        {
            get
            {
                return this.dmAllowSubstDeliveryField;
            }
            set
            {
                this.dmAllowSubstDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> dmOVM
        {
            get
            {
                return this.dmOVMField;
            }
            set
            {
                this.dmOVMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmOVMSpecified
        {
            get
            {
                return this.dmOVMFieldSpecified;
            }
            set
            {
                this.dmOVMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<bool> dmPublishOwnID
        {
            get
            {
                return this.dmPublishOwnIDField;
            }
            set
            {
                this.dmPublishOwnIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmPublishOwnIDSpecified
        {
            get
            {
                return this.dmPublishOwnIDFieldSpecified;
            }
            set
            {
                this.dmPublishOwnIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tRecipients
    {
        
        private string dbIDRecipientField;
        
        private string dmRecipientOrgUnitField;
        
        private string dmRecipientOrgUnitNumField;
        
        private string dmToHandsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dbIDRecipient
        {
            get
            {
                return this.dbIDRecipientField;
            }
            set
            {
                this.dbIDRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string dmRecipientOrgUnit
        {
            get
            {
                return this.dmRecipientOrgUnitField;
            }
            set
            {
                this.dmRecipientOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=2)]
        public string dmRecipientOrgUnitNum
        {
            get
            {
                return this.dmRecipientOrgUnitNumField;
            }
            set
            {
                this.dmRecipientOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string dmToHands
        {
            get
            {
                return this.dmToHandsField;
            }
            set
            {
                this.dmToHandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tSetMultipleConceptInput
    {
        
        private tRecipients[] dmRecipientsField;
        
        private tSetMultipleConceptInputDmEnvelope dmEnvelopeField;
        
        private tFilesArrayDmFile[] dmFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dmRecipient", IsNullable=false)]
        public tRecipients[] dmRecipients
        {
            get
            {
                return this.dmRecipientsField;
            }
            set
            {
                this.dmRecipientsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tSetMultipleConceptInputDmEnvelope dmEnvelope
        {
            get
            {
                return this.dmEnvelopeField;
            }
            set
            {
                this.dmEnvelopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dmFile", IsNullable=false)]
        public tFilesArrayDmFile[] dmFiles
        {
            get
            {
                return this.dmFilesField;
            }
            set
            {
                this.dmFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tSetMultipleConceptInputDmEnvelope : tMultipleMessageEnvelopeSub
    {
        
        private string dmTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmType
        {
            get
            {
                return this.dmTypeField;
            }
            set
            {
                this.dmTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tFilesArrayDmFile : tFile
    {
        
        private string dmMimeTypeField;
        
        private tFilesArrayDmFileDmFileMetaType dmFileMetaTypeField;
        
        private string dmFileGuidField;
        
        private string dmUpFileGuidField;
        
        private string dmFileDescrField;
        
        private string dmFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmMimeType
        {
            get
            {
                return this.dmMimeTypeField;
            }
            set
            {
                this.dmMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tFilesArrayDmFileDmFileMetaType dmFileMetaType
        {
            get
            {
                return this.dmFileMetaTypeField;
            }
            set
            {
                this.dmFileMetaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileGuid
        {
            get
            {
                return this.dmFileGuidField;
            }
            set
            {
                this.dmFileGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmUpFileGuid
        {
            get
            {
                return this.dmUpFileGuidField;
            }
            set
            {
                this.dmUpFileGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileDescr
        {
            get
            {
                return this.dmFileDescrField;
            }
            set
            {
                this.dmFileDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFormat
        {
            get
            {
                return this.dmFormatField;
            }
            set
            {
                this.dmFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public enum tFilesArrayDmFileDmFileMetaType
    {
        
        /// <remarks/>
        main,
        
        /// <remarks/>
        enclosure,
        
        /// <remarks/>
        signature,
        
        /// <remarks/>
        meta,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tFile
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dmEncodedContent", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dmXMLContent", typeof(System.Xml.XmlElement), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept")]
    public partial class tSetConceptOutput
    {
        
        private string dmIDField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetConcept1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20/koncept", Order=0)]
        public DatovkaSharp.Services.Concept.tSetConceptInput SetConcept;
        
        public SetConcept1()
        {
        }
        
        public SetConcept1(DatovkaSharp.Services.Concept.tSetConceptInput SetConcept)
        {
            this.SetConcept = SetConcept;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetConceptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetConceptResponse", Namespace="http://isds.czechpoint.cz/v20/koncept", Order=0)]
        public DatovkaSharp.Services.Concept.tSetConceptOutput SetConceptResponse1;
        
        public SetConceptResponse()
        {
        }
        
        public SetConceptResponse(DatovkaSharp.Services.Concept.tSetConceptOutput SetConceptResponse1)
        {
            this.SetConceptResponse1 = SetConceptResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMultipleConcept
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMultipleConcept", Namespace="http://isds.czechpoint.cz/v20/koncept", Order=0)]
        public DatovkaSharp.Services.Concept.tSetMultipleConceptInput SetMultipleConcept1;
        
        public SetMultipleConcept()
        {
        }
        
        public SetMultipleConcept(DatovkaSharp.Services.Concept.tSetMultipleConceptInput SetMultipleConcept1)
        {
            this.SetMultipleConcept1 = SetMultipleConcept1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMultipleConceptResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMultipleConceptResponse", Namespace="http://isds.czechpoint.cz/v20/koncept", Order=0)]
        public DatovkaSharp.Services.Concept.tSetMultipleConceptOutput SetMultipleConceptResponse1;
        
        public SetMultipleConceptResponse()
        {
        }
        
        public SetMultipleConceptResponse(DatovkaSharp.Services.Concept.tSetMultipleConceptOutput SetMultipleConceptResponse1)
        {
            this.SetMultipleConceptResponse1 = SetMultipleConceptResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SetConceptChannel : DatovkaSharp.Services.Concept.SetConcept, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SetConceptClient : System.ServiceModel.ClientBase<DatovkaSharp.Services.Concept.SetConcept>, DatovkaSharp.Services.Concept.SetConcept
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SetConceptClient() : 
                base(SetConceptClient.GetDefaultBinding(), SetConceptClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SetConceptSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SetConceptClient(EndpointConfiguration endpointConfiguration) : 
                base(SetConceptClient.GetBindingForEndpoint(endpointConfiguration), SetConceptClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SetConceptClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SetConceptClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SetConceptClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SetConceptClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SetConceptClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Concept.SetConceptResponse> DatovkaSharp.Services.Concept.SetConcept.SetConceptAsync(DatovkaSharp.Services.Concept.SetConcept1 request)
        {
            return base.Channel.SetConceptAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Concept.SetConceptResponse> SetConceptAsync(DatovkaSharp.Services.Concept.tSetConceptInput SetConcept)
        {
            DatovkaSharp.Services.Concept.SetConcept1 inValue = new DatovkaSharp.Services.Concept.SetConcept1();
            inValue.SetConcept = SetConcept;
            return ((DatovkaSharp.Services.Concept.SetConcept)(this)).SetConceptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Concept.SetMultipleConceptResponse> DatovkaSharp.Services.Concept.SetConcept.SetMultipleConceptAsync(DatovkaSharp.Services.Concept.SetMultipleConcept request)
        {
            return base.Channel.SetMultipleConceptAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Concept.SetMultipleConceptResponse> SetMultipleConceptAsync(DatovkaSharp.Services.Concept.tSetMultipleConceptInput SetMultipleConcept1)
        {
            DatovkaSharp.Services.Concept.SetMultipleConcept inValue = new DatovkaSharp.Services.Concept.SetMultipleConcept();
            inValue.SetMultipleConcept1 = SetMultipleConcept1;
            return ((DatovkaSharp.Services.Concept.SetConcept)(this)).SetMultipleConceptAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SetConceptSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SetConceptSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://cert.mojedatovaschranka.cz/asws/konceptEndpoint");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SetConceptClient.GetBindingForEndpoint(EndpointConfiguration.SetConceptSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SetConceptClient.GetEndpointAddress(EndpointConfiguration.SetConceptSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            SetConceptSoap11,
        }
    }
}
