//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatovkaSharp.Services.VoDZ
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://isds.czechpoint.cz/v20", ConfigurationName="DatovkaSharp.Services.VoDZ.dmVoDZPortType")]
    public interface dmVoDZPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.UploadAttachmentResponse1> UploadAttachmentAsync(DatovkaSharp.Services.VoDZ.UploadAttachmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.DownloadAttachmentResponse1> DownloadAttachmentAsync(DatovkaSharp.Services.VoDZ.DownloadAttachmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.CreateBigMessageResponse> CreateBigMessageAsync(DatovkaSharp.Services.VoDZ.CreateBigMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.AuthenticateBigMessageResponse1> AuthenticateBigMessageAsync(DatovkaSharp.Services.VoDZ.AuthenticateBigMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.SignedBigMessageDownloadResponse1> SignedBigMessageDownloadAsync(DatovkaSharp.Services.VoDZ.SignedBigMessageDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownloadResponse1> SignedSentBigMessageDownloadAsync(DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(tFile))]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.BigMessageDownloadResponse1> BigMessageDownloadAsync(DatovkaSharp.Services.VoDZ.BigMessageDownloadRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class UploadAttachment
    {
        
        private UploadAttachmentDmFile dmFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UploadAttachmentDmFile dmFile
        {
            get
            {
                return this.dmFileField;
            }
            set
            {
                this.dmFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class UploadAttachmentDmFile
    {
        
        private byte[] dmEncodedContentField;
        
        private string dmMimeTypeField;
        
        private string dmFileDescrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmEncodedContent
        {
            get
            {
                return this.dmEncodedContentField;
            }
            set
            {
                this.dmEncodedContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmMimeType
        {
            get
            {
                return this.dmMimeTypeField;
            }
            set
            {
                this.dmMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileDescr
        {
            get
            {
                return this.dmFileDescrField;
            }
            set
            {
                this.dmFileDescrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tHash
    {
        
        private string algorithmField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tFile
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dmEncodedContent", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dmXMLContent", typeof(System.Xml.XmlElement), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tBigMessageOutput
    {
        
        private string dmIDField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tStatus
    {
        
        private string dmStatusCodeField;
        
        private string dmStatusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmStatusCode
        {
            get
            {
                return this.dmStatusCodeField;
            }
            set
            {
                this.dmStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dmStatusMessage
        {
            get
            {
                return this.dmStatusMessageField;
            }
            set
            {
                this.dmStatusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tBigMessEnvelope
    {
        
        private string dmSenderOrgUnitField;
        
        private string dmSenderOrgUnitNumField;
        
        private string dbIDRecipientField;
        
        private string dmRecipientOrgUnitField;
        
        private string dmRecipientOrgUnitNumField;
        
        private string dmToHandsField;
        
        private string dmAnnotationField;
        
        private string dmRecipientRefNumberField;
        
        private string dmSenderRefNumberField;
        
        private string dmRecipientIdentField;
        
        private string dmSenderIdentField;
        
        private string dmLegalTitleLawField;
        
        private string dmLegalTitleYearField;
        
        private string dmLegalTitleSectField;
        
        private string dmLegalTitleParField;
        
        private string dmLegalTitlePointField;
        
        private System.Nullable<bool> dmPersonalDeliveryField;
        
        private bool dmPersonalDeliveryFieldSpecified;
        
        private System.Nullable<bool> dmAllowSubstDeliveryField;
        
        private bool dmAllowSubstDeliveryFieldSpecified;
        
        private System.Nullable<bool> dmOVMField;
        
        private bool dmOVMFieldSpecified;
        
        private tBigMessEnvelopeDmPublishOwnID dmPublishOwnIDField;
        
        private string dmTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string dmSenderOrgUnit
        {
            get
            {
                return this.dmSenderOrgUnitField;
            }
            set
            {
                this.dmSenderOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=1)]
        public string dmSenderOrgUnitNum
        {
            get
            {
                return this.dmSenderOrgUnitNumField;
            }
            set
            {
                this.dmSenderOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dbIDRecipient
        {
            get
            {
                return this.dbIDRecipientField;
            }
            set
            {
                this.dbIDRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string dmRecipientOrgUnit
        {
            get
            {
                return this.dmRecipientOrgUnitField;
            }
            set
            {
                this.dmRecipientOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=4)]
        public string dmRecipientOrgUnitNum
        {
            get
            {
                return this.dmRecipientOrgUnitNumField;
            }
            set
            {
                this.dmRecipientOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string dmToHands
        {
            get
            {
                return this.dmToHandsField;
            }
            set
            {
                this.dmToHandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string dmAnnotation
        {
            get
            {
                return this.dmAnnotationField;
            }
            set
            {
                this.dmAnnotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string dmRecipientRefNumber
        {
            get
            {
                return this.dmRecipientRefNumberField;
            }
            set
            {
                this.dmRecipientRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string dmSenderRefNumber
        {
            get
            {
                return this.dmSenderRefNumberField;
            }
            set
            {
                this.dmSenderRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string dmRecipientIdent
        {
            get
            {
                return this.dmRecipientIdentField;
            }
            set
            {
                this.dmRecipientIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string dmSenderIdent
        {
            get
            {
                return this.dmSenderIdentField;
            }
            set
            {
                this.dmSenderIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=11)]
        public string dmLegalTitleLaw
        {
            get
            {
                return this.dmLegalTitleLawField;
            }
            set
            {
                this.dmLegalTitleLawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=12)]
        public string dmLegalTitleYear
        {
            get
            {
                return this.dmLegalTitleYearField;
            }
            set
            {
                this.dmLegalTitleYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string dmLegalTitleSect
        {
            get
            {
                return this.dmLegalTitleSectField;
            }
            set
            {
                this.dmLegalTitleSectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string dmLegalTitlePar
        {
            get
            {
                return this.dmLegalTitleParField;
            }
            set
            {
                this.dmLegalTitleParField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string dmLegalTitlePoint
        {
            get
            {
                return this.dmLegalTitlePointField;
            }
            set
            {
                this.dmLegalTitlePointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<bool> dmPersonalDelivery
        {
            get
            {
                return this.dmPersonalDeliveryField;
            }
            set
            {
                this.dmPersonalDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmPersonalDeliverySpecified
        {
            get
            {
                return this.dmPersonalDeliveryFieldSpecified;
            }
            set
            {
                this.dmPersonalDeliveryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<bool> dmAllowSubstDelivery
        {
            get
            {
                return this.dmAllowSubstDeliveryField;
            }
            set
            {
                this.dmAllowSubstDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmAllowSubstDeliverySpecified
        {
            get
            {
                return this.dmAllowSubstDeliveryFieldSpecified;
            }
            set
            {
                this.dmAllowSubstDeliveryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<bool> dmOVM
        {
            get
            {
                return this.dmOVMField;
            }
            set
            {
                this.dmOVMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmOVMSpecified
        {
            get
            {
                return this.dmOVMFieldSpecified;
            }
            set
            {
                this.dmOVMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public tBigMessEnvelopeDmPublishOwnID dmPublishOwnID
        {
            get
            {
                return this.dmPublishOwnIDField;
            }
            set
            {
                this.dmPublishOwnIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmType
        {
            get
            {
                return this.dmTypeField;
            }
            set
            {
                this.dmTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tBigMessEnvelopeDmPublishOwnID
    {
        
        private string idLevelField;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string IdLevel
        {
            get
            {
                return this.idLevelField;
            }
            set
            {
                this.idLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tBigMessageInput
    {
        
        private tBigMessEnvelope dmEnvelopeField;
        
        private tBigMessageInputDmFiles dmFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tBigMessEnvelope dmEnvelope
        {
            get
            {
                return this.dmEnvelopeField;
            }
            set
            {
                this.dmEnvelopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tBigMessageInputDmFiles dmFiles
        {
            get
            {
                return this.dmFilesField;
            }
            set
            {
                this.dmFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tBigMessageInputDmFiles
    {
        
        private tBigMessageInputDmFilesDmExtFile[] dmExtFileField;
        
        private tBigMessageInputDmFilesDmFile[] dmFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dmExtFile", Order=0)]
        public tBigMessageInputDmFilesDmExtFile[] dmExtFile
        {
            get
            {
                return this.dmExtFileField;
            }
            set
            {
                this.dmExtFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dmFile", Order=1)]
        public tBigMessageInputDmFilesDmFile[] dmFile
        {
            get
            {
                return this.dmFileField;
            }
            set
            {
                this.dmFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tBigMessageInputDmFilesDmExtFile
    {
        
        private string dmFileMetaTypeField;
        
        private string dmAttIDField;
        
        private string dmAttHash1Field;
        
        private string dmAttHash1AlgField;
        
        private string dmAttHash2Field;
        
        private string dmAttHash2AlgField;
        
        private string dmFileGuidField;
        
        private string dmUpFileGuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileMetaType
        {
            get
            {
                return this.dmFileMetaTypeField;
            }
            set
            {
                this.dmFileMetaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmAttID
        {
            get
            {
                return this.dmAttIDField;
            }
            set
            {
                this.dmAttIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmAttHash1
        {
            get
            {
                return this.dmAttHash1Field;
            }
            set
            {
                this.dmAttHash1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmAttHash1Alg
        {
            get
            {
                return this.dmAttHash1AlgField;
            }
            set
            {
                this.dmAttHash1AlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmAttHash2
        {
            get
            {
                return this.dmAttHash2Field;
            }
            set
            {
                this.dmAttHash2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmAttHash2Alg
        {
            get
            {
                return this.dmAttHash2AlgField;
            }
            set
            {
                this.dmAttHash2AlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileGuid
        {
            get
            {
                return this.dmFileGuidField;
            }
            set
            {
                this.dmFileGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmUpFileGuid
        {
            get
            {
                return this.dmUpFileGuidField;
            }
            set
            {
                this.dmUpFileGuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tBigMessageInputDmFilesDmFile
    {
        
        private byte[] dmEncodedContentField;
        
        private string dmFileMetaTypeField;
        
        private string dmFileDescrField;
        
        private string dmMimeTypeField;
        
        private string dmFileGuidField;
        
        private string dmUpFileGuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmEncodedContent
        {
            get
            {
                return this.dmEncodedContentField;
            }
            set
            {
                this.dmEncodedContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileMetaType
        {
            get
            {
                return this.dmFileMetaTypeField;
            }
            set
            {
                this.dmFileMetaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileDescr
        {
            get
            {
                return this.dmFileDescrField;
            }
            set
            {
                this.dmFileDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmMimeType
        {
            get
            {
                return this.dmMimeTypeField;
            }
            set
            {
                this.dmMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileGuid
        {
            get
            {
                return this.dmFileGuidField;
            }
            set
            {
                this.dmFileGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmUpFileGuid
        {
            get
            {
                return this.dmUpFileGuidField;
            }
            set
            {
                this.dmUpFileGuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class UploadAttachmentResponse
    {
        
        private string dmAttIDField;
        
        private UploadAttachmentResponseDmAttHash1 dmAttHash1Field;
        
        private UploadAttachmentResponseDmAttHash2 dmAttHash2Field;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmAttID
        {
            get
            {
                return this.dmAttIDField;
            }
            set
            {
                this.dmAttIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UploadAttachmentResponseDmAttHash1 dmAttHash1
        {
            get
            {
                return this.dmAttHash1Field;
            }
            set
            {
                this.dmAttHash1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UploadAttachmentResponseDmAttHash2 dmAttHash2
        {
            get
            {
                return this.dmAttHash2Field;
            }
            set
            {
                this.dmAttHash2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class UploadAttachmentResponseDmAttHash1
    {
        
        private string attHashAlgField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttHashAlg
        {
            get
            {
                return this.attHashAlgField;
            }
            set
            {
                this.attHashAlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class UploadAttachmentResponseDmAttHash2
    {
        
        private string attHashAlgField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttHashAlg
        {
            get
            {
                return this.attHashAlgField;
            }
            set
            {
                this.attHashAlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadAttachmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.UploadAttachment UploadAttachment;
        
        public UploadAttachmentRequest()
        {
        }
        
        public UploadAttachmentRequest(DatovkaSharp.Services.VoDZ.UploadAttachment UploadAttachment)
        {
            this.UploadAttachment = UploadAttachment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadAttachmentResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.UploadAttachmentResponse UploadAttachmentResponse;
        
        public UploadAttachmentResponse1()
        {
        }
        
        public UploadAttachmentResponse1(DatovkaSharp.Services.VoDZ.UploadAttachmentResponse UploadAttachmentResponse)
        {
            this.UploadAttachmentResponse = UploadAttachmentResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class DownloadAttachment
    {
        
        private string dmIDField;
        
        private string attNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string attNum
        {
            get
            {
                return this.attNumField;
            }
            set
            {
                this.attNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class DownloadAttachmentResponse
    {
        
        private DownloadAttachmentResponseDmFile dmFileField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DownloadAttachmentResponseDmFile dmFile
        {
            get
            {
                return this.dmFileField;
            }
            set
            {
                this.dmFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class DownloadAttachmentResponseDmFile
    {
        
        private byte[] dmEncodedContentField;
        
        private string dmFileMetaTypeField;
        
        private string dmMimeTypeField;
        
        private string dmFileDescrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmEncodedContent
        {
            get
            {
                return this.dmEncodedContentField;
            }
            set
            {
                this.dmEncodedContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileMetaType
        {
            get
            {
                return this.dmFileMetaTypeField;
            }
            set
            {
                this.dmFileMetaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmMimeType
        {
            get
            {
                return this.dmMimeTypeField;
            }
            set
            {
                this.dmMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileDescr
        {
            get
            {
                return this.dmFileDescrField;
            }
            set
            {
                this.dmFileDescrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadAttachmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.DownloadAttachment DownloadAttachment;
        
        public DownloadAttachmentRequest()
        {
        }
        
        public DownloadAttachmentRequest(DatovkaSharp.Services.VoDZ.DownloadAttachment DownloadAttachment)
        {
            this.DownloadAttachment = DownloadAttachment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadAttachmentResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.DownloadAttachmentResponse DownloadAttachmentResponse;
        
        public DownloadAttachmentResponse1()
        {
        }
        
        public DownloadAttachmentResponse1(DatovkaSharp.Services.VoDZ.DownloadAttachmentResponse DownloadAttachmentResponse)
        {
            this.DownloadAttachmentResponse = DownloadAttachmentResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBigMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.tBigMessageInput CreateBigMessage;
        
        public CreateBigMessageRequest()
        {
        }
        
        public CreateBigMessageRequest(DatovkaSharp.Services.VoDZ.tBigMessageInput CreateBigMessage)
        {
            this.CreateBigMessage = CreateBigMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBigMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBigMessageResponse", Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.tBigMessageOutput CreateBigMessageResponse1;
        
        public CreateBigMessageResponse()
        {
        }
        
        public CreateBigMessageResponse(DatovkaSharp.Services.VoDZ.tBigMessageOutput CreateBigMessageResponse1)
        {
            this.CreateBigMessageResponse1 = CreateBigMessageResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class AuthenticateBigMessage
    {
        
        private byte[] dmMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmMessage
        {
            get
            {
                return this.dmMessageField;
            }
            set
            {
                this.dmMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class AuthenticateBigMessageResponse
    {
        
        private System.Nullable<bool> dmAuthResultField;
        
        private bool dmAuthResultFieldSpecified;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> dmAuthResult
        {
            get
            {
                return this.dmAuthResultField;
            }
            set
            {
                this.dmAuthResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmAuthResultSpecified
        {
            get
            {
                return this.dmAuthResultFieldSpecified;
            }
            set
            {
                this.dmAuthResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateBigMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.AuthenticateBigMessage AuthenticateBigMessage;
        
        public AuthenticateBigMessageRequest()
        {
        }
        
        public AuthenticateBigMessageRequest(DatovkaSharp.Services.VoDZ.AuthenticateBigMessage AuthenticateBigMessage)
        {
            this.AuthenticateBigMessage = AuthenticateBigMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateBigMessageResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.AuthenticateBigMessageResponse AuthenticateBigMessageResponse;
        
        public AuthenticateBigMessageResponse1()
        {
        }
        
        public AuthenticateBigMessageResponse1(DatovkaSharp.Services.VoDZ.AuthenticateBigMessageResponse AuthenticateBigMessageResponse)
        {
            this.AuthenticateBigMessageResponse = AuthenticateBigMessageResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class SignedBigMessageDownload
    {
        
        private string dmIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class SignedBigMessageDownloadResponse
    {
        
        private byte[] dmSignatureField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmSignature
        {
            get
            {
                return this.dmSignatureField;
            }
            set
            {
                this.dmSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignedBigMessageDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.SignedBigMessageDownload SignedBigMessageDownload;
        
        public SignedBigMessageDownloadRequest()
        {
        }
        
        public SignedBigMessageDownloadRequest(DatovkaSharp.Services.VoDZ.SignedBigMessageDownload SignedBigMessageDownload)
        {
            this.SignedBigMessageDownload = SignedBigMessageDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignedBigMessageDownloadResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.SignedBigMessageDownloadResponse SignedBigMessageDownloadResponse;
        
        public SignedBigMessageDownloadResponse1()
        {
        }
        
        public SignedBigMessageDownloadResponse1(DatovkaSharp.Services.VoDZ.SignedBigMessageDownloadResponse SignedBigMessageDownloadResponse)
        {
            this.SignedBigMessageDownloadResponse = SignedBigMessageDownloadResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class SignedSentBigMessageDownload
    {
        
        private string dmIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class SignedSentBigMessageDownloadResponse
    {
        
        private byte[] dmSignatureField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmSignature
        {
            get
            {
                return this.dmSignatureField;
            }
            set
            {
                this.dmSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignedSentBigMessageDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownload SignedSentBigMessageDownload;
        
        public SignedSentBigMessageDownloadRequest()
        {
        }
        
        public SignedSentBigMessageDownloadRequest(DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownload SignedSentBigMessageDownload)
        {
            this.SignedSentBigMessageDownload = SignedSentBigMessageDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignedSentBigMessageDownloadResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownloadResponse SignedSentBigMessageDownloadResponse;
        
        public SignedSentBigMessageDownloadResponse1()
        {
        }
        
        public SignedSentBigMessageDownloadResponse1(DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownloadResponse SignedSentBigMessageDownloadResponse)
        {
            this.SignedSentBigMessageDownloadResponse = SignedSentBigMessageDownloadResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class BigMessageDownload
    {
        
        private string dmIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class BigMessageDownloadResponse
    {
        
        private BigMessageDownloadResponseDmReturnedMessage dmReturnedMessageField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public BigMessageDownloadResponseDmReturnedMessage dmReturnedMessage
        {
            get
            {
                return this.dmReturnedMessageField;
            }
            set
            {
                this.dmReturnedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class BigMessageDownloadResponseDmReturnedMessage
    {
        
        private BigMessageDownloadResponseDmReturnedMessageDmDm dmDmField;
        
        private tHash dmHashField;
        
        private byte[] dmQTimestampField;
        
        private System.Nullable<System.DateTime> dmDeliveryTimeField;
        
        private System.Nullable<System.DateTime> dmAcceptanceTimeField;
        
        private string dmMessageStatusField;
        
        private string dmAttachmentSizeField;
        
        private string dmTypeField;
        
        private bool dmVODZField;
        
        private bool dmVODZFieldSpecified;
        
        private string attsNumField;
        
        private string specMessFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BigMessageDownloadResponseDmReturnedMessageDmDm dmDm
        {
            get
            {
                return this.dmDmField;
            }
            set
            {
                this.dmDmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public tHash dmHash
        {
            get
            {
                return this.dmHashField;
            }
            set
            {
                this.dmHashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=2)]
        public byte[] dmQTimestamp
        {
            get
            {
                return this.dmQTimestampField;
            }
            set
            {
                this.dmQTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> dmDeliveryTime
        {
            get
            {
                return this.dmDeliveryTimeField;
            }
            set
            {
                this.dmDeliveryTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dmAcceptanceTime
        {
            get
            {
                return this.dmAcceptanceTimeField;
            }
            set
            {
                this.dmAcceptanceTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string dmMessageStatus
        {
            get
            {
                return this.dmMessageStatusField;
            }
            set
            {
                this.dmMessageStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=6)]
        public string dmAttachmentSize
        {
            get
            {
                return this.dmAttachmentSizeField;
            }
            set
            {
                this.dmAttachmentSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmType
        {
            get
            {
                return this.dmTypeField;
            }
            set
            {
                this.dmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool dmVODZ
        {
            get
            {
                return this.dmVODZField;
            }
            set
            {
                this.dmVODZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmVODZSpecified
        {
            get
            {
                return this.dmVODZFieldSpecified;
            }
            set
            {
                this.dmVODZFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string attsNum
        {
            get
            {
                return this.attsNumField;
            }
            set
            {
                this.attsNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string specMessFlag
        {
            get
            {
                return this.specMessFlagField;
            }
            set
            {
                this.specMessFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class BigMessageDownloadResponseDmReturnedMessageDmDm
    {
        
        private string dmIDField;
        
        private string dbIDSenderField;
        
        private string dmSenderField;
        
        private string dmSenderAddressField;
        
        private int dmSenderTypeField;
        
        private string dmRecipientField;
        
        private string dmRecipientAddressField;
        
        private System.Nullable<bool> dmAmbiguousRecipientField;
        
        private bool dmAmbiguousRecipientFieldSpecified;
        
        private string dmSenderOrgUnitField;
        
        private string dmSenderOrgUnitNumField;
        
        private string dbIDRecipientField;
        
        private string dmRecipientOrgUnitField;
        
        private string dmRecipientOrgUnitNumField;
        
        private string dmToHandsField;
        
        private string dmAnnotationField;
        
        private string dmRecipientRefNumberField;
        
        private string dmSenderRefNumberField;
        
        private string dmRecipientIdentField;
        
        private string dmSenderIdentField;
        
        private string dmLegalTitleLawField;
        
        private string dmLegalTitleYearField;
        
        private string dmLegalTitleSectField;
        
        private string dmLegalTitleParField;
        
        private string dmLegalTitlePointField;
        
        private System.Nullable<bool> dmPersonalDeliveryField;
        
        private System.Nullable<bool> dmAllowSubstDeliveryField;
        
        private tFilesArrayDmFile[] dmFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmID
        {
            get
            {
                return this.dmIDField;
            }
            set
            {
                this.dmIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string dbIDSender
        {
            get
            {
                return this.dbIDSenderField;
            }
            set
            {
                this.dbIDSenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dmSender
        {
            get
            {
                return this.dmSenderField;
            }
            set
            {
                this.dmSenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string dmSenderAddress
        {
            get
            {
                return this.dmSenderAddressField;
            }
            set
            {
                this.dmSenderAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int dmSenderType
        {
            get
            {
                return this.dmSenderTypeField;
            }
            set
            {
                this.dmSenderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string dmRecipient
        {
            get
            {
                return this.dmRecipientField;
            }
            set
            {
                this.dmRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string dmRecipientAddress
        {
            get
            {
                return this.dmRecipientAddressField;
            }
            set
            {
                this.dmRecipientAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> dmAmbiguousRecipient
        {
            get
            {
                return this.dmAmbiguousRecipientField;
            }
            set
            {
                this.dmAmbiguousRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dmAmbiguousRecipientSpecified
        {
            get
            {
                return this.dmAmbiguousRecipientFieldSpecified;
            }
            set
            {
                this.dmAmbiguousRecipientFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string dmSenderOrgUnit
        {
            get
            {
                return this.dmSenderOrgUnitField;
            }
            set
            {
                this.dmSenderOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=9)]
        public string dmSenderOrgUnitNum
        {
            get
            {
                return this.dmSenderOrgUnitNumField;
            }
            set
            {
                this.dmSenderOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string dbIDRecipient
        {
            get
            {
                return this.dbIDRecipientField;
            }
            set
            {
                this.dbIDRecipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string dmRecipientOrgUnit
        {
            get
            {
                return this.dmRecipientOrgUnitField;
            }
            set
            {
                this.dmRecipientOrgUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=12)]
        public string dmRecipientOrgUnitNum
        {
            get
            {
                return this.dmRecipientOrgUnitNumField;
            }
            set
            {
                this.dmRecipientOrgUnitNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string dmToHands
        {
            get
            {
                return this.dmToHandsField;
            }
            set
            {
                this.dmToHandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string dmAnnotation
        {
            get
            {
                return this.dmAnnotationField;
            }
            set
            {
                this.dmAnnotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string dmRecipientRefNumber
        {
            get
            {
                return this.dmRecipientRefNumberField;
            }
            set
            {
                this.dmRecipientRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string dmSenderRefNumber
        {
            get
            {
                return this.dmSenderRefNumberField;
            }
            set
            {
                this.dmSenderRefNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string dmRecipientIdent
        {
            get
            {
                return this.dmRecipientIdentField;
            }
            set
            {
                this.dmRecipientIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string dmSenderIdent
        {
            get
            {
                return this.dmSenderIdentField;
            }
            set
            {
                this.dmSenderIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=19)]
        public string dmLegalTitleLaw
        {
            get
            {
                return this.dmLegalTitleLawField;
            }
            set
            {
                this.dmLegalTitleLawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=20)]
        public string dmLegalTitleYear
        {
            get
            {
                return this.dmLegalTitleYearField;
            }
            set
            {
                this.dmLegalTitleYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string dmLegalTitleSect
        {
            get
            {
                return this.dmLegalTitleSectField;
            }
            set
            {
                this.dmLegalTitleSectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string dmLegalTitlePar
        {
            get
            {
                return this.dmLegalTitleParField;
            }
            set
            {
                this.dmLegalTitleParField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string dmLegalTitlePoint
        {
            get
            {
                return this.dmLegalTitlePointField;
            }
            set
            {
                this.dmLegalTitlePointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<bool> dmPersonalDelivery
        {
            get
            {
                return this.dmPersonalDeliveryField;
            }
            set
            {
                this.dmPersonalDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<bool> dmAllowSubstDelivery
        {
            get
            {
                return this.dmAllowSubstDeliveryField;
            }
            set
            {
                this.dmAllowSubstDeliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=26)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dmFile", IsNullable=false)]
        public tFilesArrayDmFile[] dmFiles
        {
            get
            {
                return this.dmFilesField;
            }
            set
            {
                this.dmFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tFilesArrayDmFile : tFile
    {
        
        private string dmMimeTypeField;
        
        private tFilesArrayDmFileDmFileMetaType dmFileMetaTypeField;
        
        private string dmFileGuidField;
        
        private string dmUpFileGuidField;
        
        private string dmFileDescrField;
        
        private string dmFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmMimeType
        {
            get
            {
                return this.dmMimeTypeField;
            }
            set
            {
                this.dmMimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tFilesArrayDmFileDmFileMetaType dmFileMetaType
        {
            get
            {
                return this.dmFileMetaTypeField;
            }
            set
            {
                this.dmFileMetaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileGuid
        {
            get
            {
                return this.dmFileGuidField;
            }
            set
            {
                this.dmFileGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmUpFileGuid
        {
            get
            {
                return this.dmUpFileGuidField;
            }
            set
            {
                this.dmUpFileGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFileDescr
        {
            get
            {
                return this.dmFileDescrField;
            }
            set
            {
                this.dmFileDescrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dmFormat
        {
            get
            {
                return this.dmFormatField;
            }
            set
            {
                this.dmFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public enum tFilesArrayDmFileDmFileMetaType
    {
        
        /// <remarks/>
        main,
        
        /// <remarks/>
        enclosure,
        
        /// <remarks/>
        signature,
        
        /// <remarks/>
        meta,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BigMessageDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.BigMessageDownload BigMessageDownload;
        
        public BigMessageDownloadRequest()
        {
        }
        
        public BigMessageDownloadRequest(DatovkaSharp.Services.VoDZ.BigMessageDownload BigMessageDownload)
        {
            this.BigMessageDownload = BigMessageDownload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BigMessageDownloadResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.VoDZ.BigMessageDownloadResponse BigMessageDownloadResponse;
        
        public BigMessageDownloadResponse1()
        {
        }
        
        public BigMessageDownloadResponse1(DatovkaSharp.Services.VoDZ.BigMessageDownloadResponse BigMessageDownloadResponse)
        {
            this.BigMessageDownloadResponse = BigMessageDownloadResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface dmVoDZPortTypeChannel : DatovkaSharp.Services.VoDZ.dmVoDZPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class dmVoDZPortTypeClient : System.ServiceModel.ClientBase<DatovkaSharp.Services.VoDZ.dmVoDZPortType>, DatovkaSharp.Services.VoDZ.dmVoDZPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public dmVoDZPortTypeClient() : 
                base(dmVoDZPortTypeClient.GetDefaultBinding(), dmVoDZPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.dmVoDZPortType.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmVoDZPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(dmVoDZPortTypeClient.GetBindingForEndpoint(endpointConfiguration), dmVoDZPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmVoDZPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(dmVoDZPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmVoDZPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(dmVoDZPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmVoDZPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.UploadAttachmentResponse1> DatovkaSharp.Services.VoDZ.dmVoDZPortType.UploadAttachmentAsync(DatovkaSharp.Services.VoDZ.UploadAttachmentRequest request)
        {
            return base.Channel.UploadAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.UploadAttachmentResponse1> UploadAttachmentAsync(DatovkaSharp.Services.VoDZ.UploadAttachment UploadAttachment)
        {
            DatovkaSharp.Services.VoDZ.UploadAttachmentRequest inValue = new DatovkaSharp.Services.VoDZ.UploadAttachmentRequest();
            inValue.UploadAttachment = UploadAttachment;
            return ((DatovkaSharp.Services.VoDZ.dmVoDZPortType)(this)).UploadAttachmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.DownloadAttachmentResponse1> DatovkaSharp.Services.VoDZ.dmVoDZPortType.DownloadAttachmentAsync(DatovkaSharp.Services.VoDZ.DownloadAttachmentRequest request)
        {
            return base.Channel.DownloadAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.DownloadAttachmentResponse1> DownloadAttachmentAsync(DatovkaSharp.Services.VoDZ.DownloadAttachment DownloadAttachment)
        {
            DatovkaSharp.Services.VoDZ.DownloadAttachmentRequest inValue = new DatovkaSharp.Services.VoDZ.DownloadAttachmentRequest();
            inValue.DownloadAttachment = DownloadAttachment;
            return ((DatovkaSharp.Services.VoDZ.dmVoDZPortType)(this)).DownloadAttachmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.CreateBigMessageResponse> DatovkaSharp.Services.VoDZ.dmVoDZPortType.CreateBigMessageAsync(DatovkaSharp.Services.VoDZ.CreateBigMessageRequest request)
        {
            return base.Channel.CreateBigMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.CreateBigMessageResponse> CreateBigMessageAsync(DatovkaSharp.Services.VoDZ.tBigMessageInput CreateBigMessage)
        {
            DatovkaSharp.Services.VoDZ.CreateBigMessageRequest inValue = new DatovkaSharp.Services.VoDZ.CreateBigMessageRequest();
            inValue.CreateBigMessage = CreateBigMessage;
            return ((DatovkaSharp.Services.VoDZ.dmVoDZPortType)(this)).CreateBigMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.AuthenticateBigMessageResponse1> DatovkaSharp.Services.VoDZ.dmVoDZPortType.AuthenticateBigMessageAsync(DatovkaSharp.Services.VoDZ.AuthenticateBigMessageRequest request)
        {
            return base.Channel.AuthenticateBigMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.AuthenticateBigMessageResponse1> AuthenticateBigMessageAsync(DatovkaSharp.Services.VoDZ.AuthenticateBigMessage AuthenticateBigMessage)
        {
            DatovkaSharp.Services.VoDZ.AuthenticateBigMessageRequest inValue = new DatovkaSharp.Services.VoDZ.AuthenticateBigMessageRequest();
            inValue.AuthenticateBigMessage = AuthenticateBigMessage;
            return ((DatovkaSharp.Services.VoDZ.dmVoDZPortType)(this)).AuthenticateBigMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.SignedBigMessageDownloadResponse1> DatovkaSharp.Services.VoDZ.dmVoDZPortType.SignedBigMessageDownloadAsync(DatovkaSharp.Services.VoDZ.SignedBigMessageDownloadRequest request)
        {
            return base.Channel.SignedBigMessageDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.SignedBigMessageDownloadResponse1> SignedBigMessageDownloadAsync(DatovkaSharp.Services.VoDZ.SignedBigMessageDownload SignedBigMessageDownload)
        {
            DatovkaSharp.Services.VoDZ.SignedBigMessageDownloadRequest inValue = new DatovkaSharp.Services.VoDZ.SignedBigMessageDownloadRequest();
            inValue.SignedBigMessageDownload = SignedBigMessageDownload;
            return ((DatovkaSharp.Services.VoDZ.dmVoDZPortType)(this)).SignedBigMessageDownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownloadResponse1> DatovkaSharp.Services.VoDZ.dmVoDZPortType.SignedSentBigMessageDownloadAsync(DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownloadRequest request)
        {
            return base.Channel.SignedSentBigMessageDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownloadResponse1> SignedSentBigMessageDownloadAsync(DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownload SignedSentBigMessageDownload)
        {
            DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownloadRequest inValue = new DatovkaSharp.Services.VoDZ.SignedSentBigMessageDownloadRequest();
            inValue.SignedSentBigMessageDownload = SignedSentBigMessageDownload;
            return ((DatovkaSharp.Services.VoDZ.dmVoDZPortType)(this)).SignedSentBigMessageDownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.BigMessageDownloadResponse1> DatovkaSharp.Services.VoDZ.dmVoDZPortType.BigMessageDownloadAsync(DatovkaSharp.Services.VoDZ.BigMessageDownloadRequest request)
        {
            return base.Channel.BigMessageDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.VoDZ.BigMessageDownloadResponse1> BigMessageDownloadAsync(DatovkaSharp.Services.VoDZ.BigMessageDownload BigMessageDownload)
        {
            DatovkaSharp.Services.VoDZ.BigMessageDownloadRequest inValue = new DatovkaSharp.Services.VoDZ.BigMessageDownloadRequest();
            inValue.BigMessageDownload = BigMessageDownload;
            return ((DatovkaSharp.Services.VoDZ.dmVoDZPortType)(this)).BigMessageDownloadAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.dmVoDZPortType))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.dmVoDZPortType))
            {
                return new System.ServiceModel.EndpointAddress("https://ws2.mojedatovaschranka.cz/DS/vodz");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return dmVoDZPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.dmVoDZPortType);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return dmVoDZPortTypeClient.GetEndpointAddress(EndpointConfiguration.dmVoDZPortType);
        }
        
        public enum EndpointConfiguration
        {
            
            dmVoDZPortType,
        }
    }
}
