//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatovkaSharp.Services.Archive
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://isds.czechpoint.cz/v20", ConfigurationName="DatovkaSharp.Services.Archive.dmVoDZPortType")]
    public interface dmVoDZPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Archive.ArchiveISDSDocumentResponse1> ArchiveISDSDocumentAsync(DatovkaSharp.Services.Archive.ArchiveISDSDocumentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class ArchiveISDSDocument
    {
        
        private byte[] dmMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] dmMessage
        {
            get
            {
                return this.dmMessageField;
            }
            set
            {
                this.dmMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20")]
    public partial class tStatus
    {
        
        private string dmStatusCodeField;
        
        private string dmStatusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dmStatusCode
        {
            get
            {
                return this.dmStatusCodeField;
            }
            set
            {
                this.dmStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dmStatusMessage
        {
            get
            {
                return this.dmStatusMessageField;
            }
            set
            {
                this.dmStatusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isds.czechpoint.cz/v20")]
    public partial class ArchiveISDSDocumentResponse
    {
        
        private byte[] dmResultDocField;
        
        private System.Nullable<System.DateTime> nextStampToField;
        
        private tStatus dmStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] dmResultDoc
        {
            get
            {
                return this.dmResultDocField;
            }
            set
            {
                this.dmResultDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> nextStampTo
        {
            get
            {
                return this.nextStampToField;
            }
            set
            {
                this.nextStampToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public tStatus dmStatus
        {
            get
            {
                return this.dmStatusField;
            }
            set
            {
                this.dmStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ArchiveISDSDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Archive.ArchiveISDSDocument ArchiveISDSDocument;
        
        public ArchiveISDSDocumentRequest()
        {
        }
        
        public ArchiveISDSDocumentRequest(DatovkaSharp.Services.Archive.ArchiveISDSDocument ArchiveISDSDocument)
        {
            this.ArchiveISDSDocument = ArchiveISDSDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ArchiveISDSDocumentResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20", Order=0)]
        public DatovkaSharp.Services.Archive.ArchiveISDSDocumentResponse ArchiveISDSDocumentResponse;
        
        public ArchiveISDSDocumentResponse1()
        {
        }
        
        public ArchiveISDSDocumentResponse1(DatovkaSharp.Services.Archive.ArchiveISDSDocumentResponse ArchiveISDSDocumentResponse)
        {
            this.ArchiveISDSDocumentResponse = ArchiveISDSDocumentResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface dmVoDZPortTypeChannel : DatovkaSharp.Services.Archive.dmVoDZPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class dmVoDZPortTypeClient : System.ServiceModel.ClientBase<DatovkaSharp.Services.Archive.dmVoDZPortType>, DatovkaSharp.Services.Archive.dmVoDZPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public dmVoDZPortTypeClient() : 
                base(dmVoDZPortTypeClient.GetDefaultBinding(), dmVoDZPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.dmVoDZPortType.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmVoDZPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(dmVoDZPortTypeClient.GetBindingForEndpoint(endpointConfiguration), dmVoDZPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmVoDZPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(dmVoDZPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmVoDZPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(dmVoDZPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public dmVoDZPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.Archive.ArchiveISDSDocumentResponse1> DatovkaSharp.Services.Archive.dmVoDZPortType.ArchiveISDSDocumentAsync(DatovkaSharp.Services.Archive.ArchiveISDSDocumentRequest request)
        {
            return base.Channel.ArchiveISDSDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.Archive.ArchiveISDSDocumentResponse1> ArchiveISDSDocumentAsync(DatovkaSharp.Services.Archive.ArchiveISDSDocument ArchiveISDSDocument)
        {
            DatovkaSharp.Services.Archive.ArchiveISDSDocumentRequest inValue = new DatovkaSharp.Services.Archive.ArchiveISDSDocumentRequest();
            inValue.ArchiveISDSDocument = ArchiveISDSDocument;
            return ((DatovkaSharp.Services.Archive.dmVoDZPortType)(this)).ArchiveISDSDocumentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.dmVoDZPortType))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.dmVoDZPortType))
            {
                return new System.ServiceModel.EndpointAddress("https://ws2.mojedatovaschranka.cz/DS/arch");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return dmVoDZPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.dmVoDZPortType);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return dmVoDZPortTypeClient.GetEndpointAddress(EndpointConfiguration.dmVoDZPortType);
        }
        
        public enum EndpointConfiguration
        {
            
            dmVoDZPortType,
        }
    }
}
