//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatovkaSharp.Services.ChangePassword
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://isds.czechpoint.cz/v20/asws", ConfigurationName="DatovkaSharp.Services.ChangePassword.ChangePassword")]
    public interface ChangePassword
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.ChangePassword.SendSMSCodeResponse> SendSMSCodeAsync(DatovkaSharp.Services.ChangePassword.SendSMSCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.ChangePassword.ChangePasswordOTPResponse> ChangePasswordOTPAsync(DatovkaSharp.Services.ChangePassword.ChangePasswordOTPRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/asws")]
    public partial class tSendSMSCode
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/asws")]
    public partial class tChngPasswInputOTP
    {
        
        private string dbOldPasswordField;
        
        private string dbNewPasswordField;
        
        private tAuthType dbOTPTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dbOldPassword
        {
            get
            {
                return this.dbOldPasswordField;
            }
            set
            {
                this.dbOldPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dbNewPassword
        {
            get
            {
                return this.dbNewPasswordField;
            }
            set
            {
                this.dbNewPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public tAuthType dbOTPType
        {
            get
            {
                return this.dbOTPTypeField;
            }
            set
            {
                this.dbOTPTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/asws")]
    public enum tAuthType
    {
        
        /// <remarks/>
        TOTP,
        
        /// <remarks/>
        HOTP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/asws")]
    public partial class tDbReqStatus
    {
        
        private string dbStatusCodeField;
        
        private string dbStatusMessageField;
        
        private string dbStatusRefNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dbStatusCode
        {
            get
            {
                return this.dbStatusCodeField;
            }
            set
            {
                this.dbStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dbStatusMessage
        {
            get
            {
                return this.dbStatusMessageField;
            }
            set
            {
                this.dbStatusMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string dbStatusRefNumber
        {
            get
            {
                return this.dbStatusRefNumberField;
            }
            set
            {
                this.dbStatusRefNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isds.czechpoint.cz/v20/asws")]
    public partial class tReqStatusOutput
    {
        
        private tDbReqStatus dbStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public tDbReqStatus dbStatus
        {
            get
            {
                return this.dbStatusField;
            }
            set
            {
                this.dbStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20/asws", Order=0)]
        public DatovkaSharp.Services.ChangePassword.tSendSMSCode SendSMSCode;
        
        public SendSMSCodeRequest()
        {
        }
        
        public SendSMSCodeRequest(DatovkaSharp.Services.ChangePassword.tSendSMSCode SendSMSCode)
        {
            this.SendSMSCode = SendSMSCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSCodeResponse", Namespace="http://isds.czechpoint.cz/v20/asws", Order=0)]
        public DatovkaSharp.Services.ChangePassword.tReqStatusOutput SendSMSCodeResponse1;
        
        public SendSMSCodeResponse()
        {
        }
        
        public SendSMSCodeResponse(DatovkaSharp.Services.ChangePassword.tReqStatusOutput SendSMSCodeResponse1)
        {
            this.SendSMSCodeResponse1 = SendSMSCodeResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordOTPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isds.czechpoint.cz/v20/asws", Order=0)]
        public DatovkaSharp.Services.ChangePassword.tChngPasswInputOTP ChangePasswordOTP;
        
        public ChangePasswordOTPRequest()
        {
        }
        
        public ChangePasswordOTPRequest(DatovkaSharp.Services.ChangePassword.tChngPasswInputOTP ChangePasswordOTP)
        {
            this.ChangePasswordOTP = ChangePasswordOTP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordOTPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordOTPResponse", Namespace="http://isds.czechpoint.cz/v20/asws", Order=0)]
        public DatovkaSharp.Services.ChangePassword.tReqStatusOutput ChangePasswordOTPResponse1;
        
        public ChangePasswordOTPResponse()
        {
        }
        
        public ChangePasswordOTPResponse(DatovkaSharp.Services.ChangePassword.tReqStatusOutput ChangePasswordOTPResponse1)
        {
            this.ChangePasswordOTPResponse1 = ChangePasswordOTPResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ChangePasswordChannel : DatovkaSharp.Services.ChangePassword.ChangePassword, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ChangePasswordClient : System.ServiceModel.ClientBase<DatovkaSharp.Services.ChangePassword.ChangePassword>, DatovkaSharp.Services.ChangePassword.ChangePassword
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ChangePasswordClient() : 
                base(ChangePasswordClient.GetDefaultBinding(), ChangePasswordClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ChangePasswordSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChangePasswordClient(EndpointConfiguration endpointConfiguration) : 
                base(ChangePasswordClient.GetBindingForEndpoint(endpointConfiguration), ChangePasswordClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChangePasswordClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ChangePasswordClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChangePasswordClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ChangePasswordClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ChangePasswordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.ChangePassword.SendSMSCodeResponse> DatovkaSharp.Services.ChangePassword.ChangePassword.SendSMSCodeAsync(DatovkaSharp.Services.ChangePassword.SendSMSCodeRequest request)
        {
            return base.Channel.SendSMSCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.ChangePassword.SendSMSCodeResponse> SendSMSCodeAsync(DatovkaSharp.Services.ChangePassword.tSendSMSCode SendSMSCode)
        {
            DatovkaSharp.Services.ChangePassword.SendSMSCodeRequest inValue = new DatovkaSharp.Services.ChangePassword.SendSMSCodeRequest();
            inValue.SendSMSCode = SendSMSCode;
            return ((DatovkaSharp.Services.ChangePassword.ChangePassword)(this)).SendSMSCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatovkaSharp.Services.ChangePassword.ChangePasswordOTPResponse> DatovkaSharp.Services.ChangePassword.ChangePassword.ChangePasswordOTPAsync(DatovkaSharp.Services.ChangePassword.ChangePasswordOTPRequest request)
        {
            return base.Channel.ChangePasswordOTPAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatovkaSharp.Services.ChangePassword.ChangePasswordOTPResponse> ChangePasswordOTPAsync(DatovkaSharp.Services.ChangePassword.tChngPasswInputOTP ChangePasswordOTP)
        {
            DatovkaSharp.Services.ChangePassword.ChangePasswordOTPRequest inValue = new DatovkaSharp.Services.ChangePassword.ChangePasswordOTPRequest();
            inValue.ChangePasswordOTP = ChangePasswordOTP;
            return ((DatovkaSharp.Services.ChangePassword.ChangePassword)(this)).ChangePasswordOTPAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ChangePasswordSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ChangePasswordSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://www.mojedatovaschranka.cz/asws/changePassword");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ChangePasswordClient.GetBindingForEndpoint(EndpointConfiguration.ChangePasswordSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ChangePasswordClient.GetEndpointAddress(EndpointConfiguration.ChangePasswordSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            ChangePasswordSoap11,
        }
    }
}
